import type { AutoBattlerMinionDef } from './autoBattler';

type Loc = { ru: string; en: string };
const L = (ru: string, en: string): Loc => ({ ru, en });

/**
 * Starter tavern. Each tribe keeps one identity with two or three ways to scale it:
 * - beasts breed tokens and grow when the pack dies or arrives (deathrattle, friendlyDeath, friendlySummon);
 * - mechs shield up and feed on popped shields, buys and bolted-on parts (shieldPop, buy, endTurn tokens);
 * - pirates chase gold and grow with every action — end of turn, refreshes, attacks (gold, reroll, friendlyAttack);
 * - undead come back and feast on their dead (reborn, friendlyDeath, deathrattle buffs, Grave Echo);
 * - dragons hit first and hit again (startCombat, friendlyAttack, battlecry synergy);
 * - demons grow three ways: plain demon buffs (buy/play/endTurn), a blood price paid by the hero (selfDamage → buffs, the
 *   Tier 2 Soul Warden guards the hero) and gluttony — eating tavern minions for their stats (devour → tavern buffs, the
 *   Tier 6 Gargoyle feeds the whole board at end of turn);
 * - neutrals sell the cross-tribe plans: menagerie counts, hand buffs, spell synergy, triples, and the two echoes.
 * Tavern spells sit in the rightmost slots at their own price. Effects are data (see AutoBattlerEffect); the server interprets them.
 */
export const starterAutoBattlerMinions: AutoBattlerMinionDef[] = [
  // ── Tokens (never offered) ──
  { id: 'ab-token-1-1', name: L('Заводской Петрович', 'Factory Petrovich'), tavernTier: 1, attack: 1, health: 1, keywords: [], tribes: ['neutral'], token: true, inTavern: false, inDiscover: false },
  { id: 'ab-token-rat', name: L('Крысёныш', 'Rat Pup'), tavernTier: 1, attack: 1, health: 1, keywords: [], tribes: ['beast'], token: true, inTavern: false, inDiscover: false },
  { id: 'ab-token-skel', name: L('Скелет-слуга', 'Bone Servant'), tavernTier: 1, attack: 2, health: 1, keywords: [], tribes: ['undead'], token: true, inTavern: false, inDiscover: false },
  { id: 'ab-token-cub', name: L('Хряк-бугай', 'Boar Brute'), tavernTier: 3, attack: 3, health: 3, keywords: [], tribes: ['beast'], token: true, inTavern: false, inDiscover: false },
  { id: 'ab-token-microbot', name: L('Ученик сварщика', 'Welder Apprentice'), tavernTier: 1, attack: 1, health: 1, keywords: [], tribes: ['mech'], token: true, inTavern: false, inDiscover: false },
  { id: 'ab-token-hound', name: L('Гончая', 'Hound'), tavernTier: 1, attack: 2, health: 1, keywords: [], tribes: ['beast'], token: true, inTavern: false, inDiscover: false },
  { id: 'ab-token-raptor', name: L('Кабан-хищник', 'Boar Raptor'), tavernTier: 2, attack: 3, health: 2, keywords: [], tribes: ['beast'], token: true, inTavern: false, inDiscover: false },
  { id: 'ab-token-drake', name: L('Дракончик', 'Drake'), tavernTier: 1, attack: 2, health: 2, keywords: [], tribes: ['dragon'], token: true, inTavern: false, inDiscover: false },
  { id: 'ab-token-shade', name: L('Тень', 'Shade'), tavernTier: 1, attack: 1, health: 1, keywords: ['reborn'], tribes: ['undead'], token: true, inTavern: false, inDiscover: false },
  { id: 'ab-token-sailor', name: L('Матрос', 'Sailor'), tavernTier: 1, attack: 1, health: 1, keywords: [], tribes: ['pirate'], token: true, inTavern: false, inDiscover: false },
  { id: 'ab-token-bouncer', name: L('Нанятый вышибала', 'Hired Bouncer'), tavernTier: 4, attack: 4, health: 4, keywords: ['taunt'], tribes: ['neutral'], token: true, inTavern: false, inDiscover: false },
  { id: 'ab-token-imp', name: L('Бесёнок', 'Imp'), tavernTier: 1, attack: 1, health: 1, keywords: [], tribes: ['demon'], token: true, inTavern: false, inDiscover: false },

  // ── Tavern spells (rightmost slots, own price; see AutoBattlerSpell) ──
  { id: 'ab-discover', name: L('Открытие', 'Discover'), description: L('Выберите одно из трёх существ.', 'Discover a minion.'), tavernTier: 1, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'discover' }, generated: true, inTavern: false, inDiscover: false },
  // Tier 1
  { id: 'ab-spell-coin', name: L('Монета', 'Coin'), description: L('Получите 1 доллар.', 'Gain $1.'), tavernTier: 1, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'coin', cost: 1, amount: 1 }, poolCopies: 10, inDiscover: false },
  { id: 'ab-spell-taunt', name: L('Щит трактирщика', "Innkeeper's Shield"), description: L('Существо получает провокацию.', 'Give a minion Taunt.'), tavernTier: 1, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'keyword', cost: 1, keyword: 'taunt' }, poolCopies: 8, inDiscover: false },
  { id: 'ab-spell-snack', name: L('Закуска', 'Bar Snack'), description: L('Существо получает +1/+1.', 'Give a minion +1/+1.'), tavernTier: 1, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'tonic', cost: 1, attack: 1, health: 1 }, poolCopies: 10, inDiscover: false },
  { id: 'ab-spell-refresh', name: L('Свежая партия', 'Fresh Batch'), description: L('Обновите лавку; новые существа в ней получают +1/+1.', 'Refresh the tavern; its new minions get +1/+1.'), tavernTier: 1, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'refresh', cost: 1, attack: 1, health: 1 }, poolCopies: 8, inDiscover: false },
  { id: 'ab-spell-deposit', name: L('Задаток', 'Down Payment'), description: L('На следующий ход: +3 доллара.', 'Next turn: +$3.'), tavernTier: 1, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'bank', cost: 2, amount: 3 }, poolCopies: 6, inDiscover: false },
  // Tier 2
  { id: 'ab-spell-tonic', name: L('Настойка', 'Tonic'), description: L('Существо получает +2/+2.', 'Give a minion +2/+2.'), tavernTier: 2, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'tonic', cost: 2, attack: 2, health: 2 }, poolCopies: 8, inDiscover: false },
  { id: 'ab-spell-polish', name: L('Полировка', 'Polish'), description: L('Существо получает щит.', 'Give a minion Divine Shield.'), tavernTier: 2, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'keyword', cost: 2, keyword: 'divineShield' }, poolCopies: 6, inDiscover: false },
  { id: 'ab-spell-drill', name: L('Муштра', 'Drill'), description: L('Существа в руке получают +1/+1.', 'Minions in your hand get +1/+1.'), tavernTier: 2, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'handBuff', cost: 2, attack: 1, health: 1 }, poolCopies: 6, inDiscover: false },
  { id: 'ab-spell-ale', name: L('Боевой эль', 'War Ale'), description: L('Существо получает +3/+3 до конца хода.', 'Give a minion +3/+3 for this turn only.'), tavernTier: 2, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'temp', cost: 1, attack: 3, health: 3 }, poolCopies: 8, inDiscover: false },
  // Tier 3
  { id: 'ab-spell-elevator', name: L('Чёрная лестница', 'Back Stairs'), description: L('Улучшение таверны стоит на 3 доллара дешевле.', 'Your tavern upgrade costs $3 less.'), tavernTier: 3, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'upgrade', cost: 2, amount: 3 }, poolCopies: 6, inDiscover: false },
  { id: 'ab-spell-takings', name: L('Выручка', 'Takings'), description: L('Получите 2 доллара.', 'Gain $2.'), tavernTier: 3, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'coin', cost: 1, amount: 2 }, poolCopies: 6, inDiscover: false },
  { id: 'ab-spell-rally', name: L('Клич трактира', 'Tavern Rally'), description: L('Ваши существа получают +1/+1.', 'Your minions get +1/+1.'), tavernTier: 3, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'tribeBuff', cost: 3, tribe: 'all', attack: 1, health: 1 }, poolCopies: 6, inDiscover: false },
  { id: 'ab-spell-reborn', name: L('Свиток возвращения', 'Scroll of Return'), description: L('Существо получает возрождение.', 'Give a minion Reborn.'), tavernTier: 3, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'keyword', cost: 3, keyword: 'reborn' }, poolCopies: 5, inDiscover: false },
  // Tier 4
  { id: 'ab-spell-venom', name: L('Яд из подвала', 'Cellar Venom'), description: L('Существо получает яд.', 'Give a minion Poisonous.'), tavernTier: 4, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'keyword', cost: 4, keyword: 'poisonous' }, poolCopies: 5, inDiscover: false },
  { id: 'ab-spell-gale', name: L('Порыв ветра', 'Gale'), description: L('Существо получает двойной удар.', 'Give a minion Windfury.'), tavernTier: 4, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'keyword', cost: 3, keyword: 'windfury' }, poolCopies: 5, inDiscover: false },
  { id: 'ab-spell-choice', name: L('Выбор из помёта', 'Pick of the Litter'), description: L('Выберите одно из трёх существ вашего тира.', 'Discover a minion of your tier.'), tavernTier: 4, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'discover', cost: 3 }, poolCopies: 5, inDiscover: false },
  // Tier 5
  { id: 'ab-spell-feast', name: L('Пир', 'Feast'), description: L('Ваши существа получают +2/+2.', 'Your minions get +2/+2.'), tavernTier: 5, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'tribeBuff', cost: 4, tribe: 'all', attack: 2, health: 2 }, poolCopies: 5, inDiscover: false },
  { id: 'ab-spell-reinforce', name: L('Подкрепление', 'Reinforcements'), description: L('Призывает Нанятого вышибалу 4/4 с провокацией.', 'Summon a 4/4 Hired Bouncer with Taunt.'), tavernTier: 5, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'summon', cost: 3, summonId: 'ab-token-bouncer', count: 1 }, poolCopies: 5, inDiscover: false },
  // Tier 6
  { id: 'ab-spell-decree', name: L('Королевский указ', 'Royal Decree'), description: L('Ваши существа получают +4/+4.', 'Your minions get +4/+4.'), tavernTier: 6, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'tribeBuff', cost: 5, tribe: 'all', attack: 4, health: 4 }, poolCopies: 4, inDiscover: false },
  { id: 'ab-spell-treasure', name: L('Клад', 'Buried Treasure'), description: L('Получите 5 долларов.', 'Gain $5.'), tavernTier: 6, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'coin', cost: 2, amount: 5 }, poolCopies: 4, inDiscover: false },
  // Demon spells (only offered when demons play): the blood price, gluttony, fattening the counter and the plain demon rally.
  { id: 'ab-spell-blood-pact', name: L('Кровавый договор', 'Blood Pact'), description: L('Ваш герой получает 2 урона. Ваши демоны получают +2/+2.', 'Your hero takes 2 damage. Your demons get +2/+2.'), tavernTier: 2, attack: 0, health: 1, keywords: [], tribes: ['demon'], spell: { kind: 'selfDamage', cost: 1, amount: 2, tribe: 'demon', attack: 2, health: 2 }, poolCopies: 8, inDiscover: false },
  { id: 'ab-spell-gluttony', name: L('Обжорство', 'Gluttony'), description: L('Ваше существо пожирает существо из лавки и получает его характеристики.', 'A friendly minion devours a tavern minion and gains its stats.'), tavernTier: 3, attack: 0, health: 1, keywords: [], tribes: ['demon'], spell: { kind: 'devour', cost: 2, count: 1 }, poolCopies: 6, inDiscover: false },
  { id: 'ab-spell-fattening', name: L('Откорм', 'Fattening'), description: L('Существа в лавке получают +2/+2.', 'Minions in the tavern get +2/+2.'), tavernTier: 3, attack: 0, health: 1, keywords: [], tribes: ['demon'], spell: { kind: 'tavernBuff', cost: 1, attack: 2, health: 2 }, poolCopies: 6, inDiscover: false },
  { id: 'ab-spell-abyss-call', name: L('Зов бездны', 'Call of the Abyss'), description: L('Ваш герой получает 3 урона. Ваши демоны получают +4/+4.', 'Your hero takes 3 damage. Your demons get +4/+4.'), tavernTier: 5, attack: 0, health: 1, keywords: [], tribes: ['demon'], spell: { kind: 'selfDamage', cost: 3, amount: 3, tribe: 'demon', attack: 4, health: 4 }, poolCopies: 4, inDiscover: false },

  // ══════════════════════════════ Tier 1 ══════════════════════════════
  // Beasts
  { id: 'ab-rat-pack', name: L('Крысиная стая', 'Rat Pack'), description: L('Предсмертный хрип: призывает Крысёныша 1/1.', 'Deathrattle: summon a 1/1 Rat Pup.'), tavernTier: 1, attack: 2, health: 2, keywords: ['deathrattle'], tribes: ['beast'], deathrattle: { summonId: 'ab-token-rat', count: 1 } },
  { id: 'ab-cub', name: L('Медвежонок', 'Cub'), description: L('После покупки зверя: +1/+1.', 'After you buy a beast: +1/+1.'), tavernTier: 1, attack: 1, health: 1, keywords: [], tribes: ['beast'], effects: [{ trigger: 'buy', onTribe: 'beast', target: 'self', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-egg', name: L('Яйцо кабана-хищника', 'Boar Raptor Egg'), description: L('Предсмертный хрип: призывает Кабана-хищника 3/2. Не атакует.', 'Deathrattle: summon a 3/2 Boar Raptor. Cannot attack.'), tavernTier: 1, attack: 0, health: 3, keywords: ['cannotAttack', 'deathrattle'], tribes: ['beast'], deathrattle: { summonId: 'ab-token-raptor', count: 1 } },
  { id: 'ab-magpie', name: L('Сорока', 'Magpie'), description: L('После покупки существа: звери в руке получают +1/+1.', 'After you buy a minion: beasts in your hand get +1/+1.'), tavernTier: 1, attack: 1, health: 2, keywords: [], tribes: ['beast'], effects: [{ trigger: 'buy', target: 'hand', tribe: 'beast', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-bone-dog', name: L('Костяная псина', 'Bone Dog'), description: L('Зверь и нежить.', 'Beast and undead.'), tavernTier: 1, attack: 2, health: 1, keywords: ['reborn'], tribes: ['beast', 'undead'] },
  { id: 'ab-bilge-rat', name: L('Трюмная крыса', 'Bilge Rat'), description: L('Зверь и пират. Продаётся за 2 доллара.', 'Beast and pirate. Sells for $2.'), tavernTier: 1, attack: 1, health: 2, keywords: [], tribes: ['beast', 'pirate'], effects: [{ trigger: 'sell', action: { kind: 'gold', amount: 1 } }] },
  // Mechs
  { id: 'ab-ward', name: L('Страж', 'Ward'), tavernTier: 1, attack: 1, health: 3, keywords: ['taunt'], tribes: ['mech'] },
  { id: 'ab-aegis', name: L('Эгида', 'Aegis'), tavernTier: 1, attack: 2, health: 2, keywords: ['divineShield'], tribes: ['mech'] },
  { id: 'ab-scrap-bot', name: L('Хламобот', 'Scrap Bot'), description: L('Предсмертный хрип: призывает Ученика сварщика 1/1.', 'Deathrattle: summon a 1/1 Welder Apprentice.'), tavernTier: 1, attack: 1, health: 2, keywords: ['deathrattle'], tribes: ['mech'], deathrattle: { summonId: 'ab-token-microbot', count: 1 } },
  { id: 'ab-tinkerer', name: L('Жестянщик', 'Tinkerer'), description: L('Боевой клич: другой случайный ваш механизм получает +1/+1.', 'Battlecry: another random friendly mech gets +1/+1.'), tavernTier: 1, attack: 2, health: 1, keywords: ['battlecry'], tribes: ['mech'], effects: [{ trigger: 'battlecry', target: 'random', tribe: 'mech', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-annoyer', name: L('Бесилка', 'Annoyer'), tavernTier: 1, attack: 1, health: 2, keywords: ['taunt', 'divineShield'], tribes: ['mech'] },
  { id: 'ab-shield-mite', name: L('Клещ-сварщик', 'Shield Mite Welder'), description: L('Когда другое ваше существо теряет щит: +1/+1.', 'Whenever another friendly minion loses Divine Shield: +1/+1.'), tavernTier: 1, attack: 1, health: 1, keywords: ['divineShield'], tribes: ['mech'], effects: [{ trigger: 'shieldPop', target: 'self', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-tin-soldier', name: L('Оловянный сварщик', 'Tin Welder'), description: L('Боевой клич: другой случайный ваш механизм получает щит.', 'Battlecry: another random friendly mech gains Divine Shield.'), tavernTier: 1, attack: 1, health: 2, keywords: ['battlecry'], tribes: ['mech'], effects: [{ trigger: 'battlecry', target: 'random', tribe: 'mech', action: { kind: 'keyword', keyword: 'divineShield' } }] },
  // Pirates
  { id: 'ab-broker', name: L('Маклер', 'Broker'), description: L('Боевой клич: +1 доллар.', 'Battlecry: gain $1.'), tavernTier: 1, attack: 1, health: 2, keywords: ['battlecry'], tribes: ['pirate'], battlecryId: 'ab-bc-gold', effects: [{ trigger: 'battlecry', action: { kind: 'gold', amount: 1 } }] },
  { id: 'ab-deckhand', name: L('Юнга', 'Deckhand'), description: L('В конце хода: +1 к атаке.', 'End of turn: +1 Attack.'), tavernTier: 1, attack: 2, health: 1, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'endTurn', target: 'self', action: { kind: 'buff', attack: 1, health: 0 } }] },
  { id: 'ab-swab', name: L('Швабра', 'Swab'), description: L('Продаётся за 2 доллара.', 'Sells for $2.'), tavernTier: 1, attack: 1, health: 1, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'sell', action: { kind: 'gold', amount: 1 } }] },
  { id: 'ab-sky-pirate', name: L('Шкет', 'Sky Pirate'), description: L('Предсмертный хрип: призывает Матроса 1/1.', 'Deathrattle: summon a 1/1 Sailor.'), tavernTier: 1, attack: 2, health: 1, keywords: ['deathrattle'], tribes: ['pirate'], deathrattle: { summonId: 'ab-token-sailor', count: 1 } },
  { id: 'ab-cabin-boy', name: L('Каютный юнга', 'Cabin Boy'), description: L('После атаки другого вашего пирата: +1/+1.', 'After another friendly pirate attacks: +1/+1.'), tavernTier: 1, attack: 1, health: 3, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'friendlyAttack', onTribe: 'pirate', target: 'self', action: { kind: 'buff', attack: 1, health: 1 } }] },
  // Undead
  { id: 'ab-ghoul', name: L('Гуль', 'Ghoul'), tavernTier: 1, attack: 2, health: 1, keywords: ['reborn'], tribes: ['undead'] },
  { id: 'ab-harvester', name: L('Жнец душ', 'Soul Harvester'), description: L('Предсмертный хрип: ваша нежить получает +1/+1.', 'Deathrattle: your undead get +1/+1.'), tavernTier: 1, attack: 1, health: 2, keywords: ['deathrattle'], tribes: ['undead'], effects: [{ trigger: 'deathrattle', target: 'friendly', tribe: 'undead', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-corpse-flower', name: L('Трупоцвет', 'Corpse Flower'), description: L('Когда ваша нежить погибает: +2 к атаке.', 'Whenever a friendly undead dies: +2 Attack.'), tavernTier: 1, attack: 0, health: 3, keywords: ['taunt'], tribes: ['undead'], effects: [{ trigger: 'friendlyDeath', onTribe: 'undead', target: 'self', action: { kind: 'buff', attack: 2, health: 0 } }] },
  // Dragons
  { id: 'ab-whelpling', name: L('Змеёныш-дракон', 'Whelpling'), description: L('После атаки другого вашего дракона: +1 к атаке.', 'After another friendly dragon attacks: +1 Attack.'), tavernTier: 1, attack: 2, health: 1, keywords: [], tribes: ['dragon'], effects: [{ trigger: 'friendlyAttack', onTribe: 'dragon', target: 'self', action: { kind: 'buff', attack: 1, health: 0 } }] },
  { id: 'ab-red-whelp', name: L('Огненный змей', 'Red Whelp'), description: L('В начале боя: +1 к атаке за каждого вашего дракона.', 'Start of combat: +1 Attack for each friendly dragon.'), tavernTier: 1, attack: 1, health: 2, keywords: [], tribes: ['dragon'], effects: [{ trigger: 'startCombat', target: 'self', per: 'minions', perTribe: 'dragon', action: { kind: 'buff', attack: 1, health: 0 } }] },
  // Demons
  { id: 'ab-imp-pack', name: L('Стайка бесов', 'Imp Pack'), description: L('Предсмертный хрип: призывает Бесёнка 1/1.', 'Deathrattle: summon a 1/1 Imp.'), tavernTier: 1, attack: 1, health: 2, keywords: ['deathrattle'], tribes: ['demon'], deathrattle: { summonId: 'ab-token-imp', count: 1 } },
  { id: 'ab-pain-fiend', name: L('Любитель боли', 'Pain Fiend'), description: L('После урона герою от ваших демонов: +1/+1.', 'After your hero takes damage from your demons: +1/+1.'), tavernTier: 1, attack: 1, health: 3, keywords: [], tribes: ['demon'], effects: [{ trigger: 'selfDamage', target: 'self', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-gobbler', name: L('Обжора', 'Gobbler'), description: L('Боевой клич: пожирает существо из лавки и получает его характеристики.', 'Battlecry: devour a tavern minion and gain its stats.'), tavernTier: 1, attack: 1, health: 1, keywords: ['battlecry'], tribes: ['demon'], effects: [{ trigger: 'battlecry', target: 'self', action: { kind: 'devour', count: 1 } }] },
  { id: 'ab-imp-reveler', name: L('Бес-кутила', 'Imp Reveler'), description: L('После покупки демона: +1/+1.', 'After you buy a demon: +1/+1.'), tavernTier: 1, attack: 2, health: 1, keywords: [], tribes: ['demon'], effects: [{ trigger: 'buy', onTribe: 'demon', target: 'self', action: { kind: 'buff', attack: 1, health: 1 } }] },
  // Neutrals
  { id: 'ab-drunk', name: L('Пьянчуга', 'Drunk'), tavernTier: 1, attack: 2, health: 3, keywords: [], tribes: ['neutral'] },
  { id: 'ab-sellsword', name: L('Бродячий наёмник', 'Wandering Sellsword'), description: L('После обновления лавки: +1 к атаке.', 'After you refresh the tavern: +1 Attack.'), tavernTier: 1, attack: 1, health: 2, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'reroll', target: 'self', action: { kind: 'buff', attack: 1, health: 0 } }] },
  { id: 'ab-scribe', name: L('Трактирный писарь', 'Tavern Scribe'), description: L('В конце хода: существа в руке получают +1/+1.', 'End of turn: minions in your hand get +1/+1.'), tavernTier: 1, attack: 1, health: 2, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'endTurn', target: 'hand', tribe: 'all', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-zookeeper', name: L('Смотритель зверинца', 'Menagerie Keeper'), description: L('Боевой клич: +1/+1 за каждый тип существ на столе.', 'Battlecry: +1/+1 for each minion type on your board.'), tavernTier: 1, attack: 2, health: 2, keywords: ['battlecry'], tribes: ['neutral'], effects: [{ trigger: 'battlecry', target: 'self', per: 'tribes', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-hedge-apprentice', name: L('Ученица знахарки', 'Hedge Apprentice'), description: L('После заклинания таверны: +1/+1.', 'After you play a tavern spell: +1/+1.'), tavernTier: 1, attack: 1, health: 2, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'spell', target: 'self', action: { kind: 'buff', attack: 1, health: 1 } }] },

  // ══════════════════════════════ Tier 2 ══════════════════════════════
  // Beasts
  { id: 'ab-viper', name: L('Гадюка', 'Viper'), tavernTier: 2, attack: 1, health: 2, keywords: ['poisonous'], tribes: ['beast'] },
  { id: 'ab-breeder', name: L('Заводчик', 'Breeder'), description: L('Когда ваш зверь призван в бою: +1/+1.', 'Whenever a friendly beast is summoned in combat: +1/+1.'), tavernTier: 2, attack: 2, health: 2, keywords: [], tribes: ['beast'], effects: [{ trigger: 'friendlySummon', onTribe: 'beast', target: 'self', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-alpha', name: L('Вожак', 'Alpha'), description: L('Другие ваши звери получают +2 к атаке в бою.', 'Your other beasts have +2 Attack in combat.'), tavernTier: 3, attack: 2, health: 3, keywords: [], tribes: ['beast'], auraId: 'ab-aura-beasts', effects: [{ trigger: 'aura', tribe: 'beast', action: { kind: 'aura', attack: 2 } }] },
  { id: 'ab-parrot', name: L('Попугай', 'Parrot'), description: L('После розыгрыша зверя: +1/+1.', 'After you play a beast: +1/+1.'), tavernTier: 2, attack: 2, health: 1, keywords: [], tribes: ['beast'], effects: [{ trigger: 'play', onTribe: 'beast', target: 'self', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-nest', name: L('Гнездо', 'Nest'), description: L('Предсмертный хрип: призывает двух Крысят 1/1.', 'Deathrattle: summon two 1/1 Rat Pups.'), tavernTier: 2, attack: 1, health: 3, keywords: ['deathrattle'], tribes: ['beast'], deathrattle: { summonId: 'ab-token-rat', count: 2 } },
  { id: 'ab-hyena', name: L('Гиена', 'Hyena'), description: L('Когда ваш зверь погибает: +2/+1.', 'Whenever a friendly beast dies: +2/+1.'), tavernTier: 2, attack: 2, health: 2, keywords: [], tribes: ['beast'], effects: [{ trigger: 'friendlyDeath', onTribe: 'beast', target: 'self', action: { kind: 'buff', attack: 2, health: 1 } }] },
  { id: 'ab-kennel', name: L('Псарня', 'Hound Kennel'), description: L('Предсмертный хрип: призывает двух Гончих 2/1.', 'Deathrattle: summon two 2/1 Hounds.'), tavernTier: 2, attack: 1, health: 4, keywords: ['deathrattle'], tribes: ['beast'], deathrattle: { summonId: 'ab-token-hound', count: 2 } },
  { id: 'ab-brood', name: L('Выводок', 'Brood'), description: L('После розыгрыша зверя: он получает +1/+1.', 'After you play a beast, give it +1/+1.'), tavernTier: 2, attack: 1, health: 2, keywords: [], tribes: ['beast'], effects: [{ trigger: 'play', onTribe: 'beast', target: 'subject', action: { kind: 'buff', attack: 1, health: 1 } }] },
  // Mechs
  { id: 'ab-shieldbot', name: L('Щитобот', 'Shieldbot'), description: L('Боевой клич: соседи получают +1/+1.', 'Battlecry: adjacent minions get +1/+1.'), tavernTier: 2, attack: 1, health: 3, keywords: ['taunt', 'battlecry'], tribes: ['mech'], effects: [{ trigger: 'battlecry', target: 'adjacent', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-mechanic', name: L('Механик', 'Mechanic'), description: L('Триплет: другие ваши механизмы получают +1/+1.', 'After you make a triple: your other mechs get +1/+1.'), tavernTier: 2, attack: 2, health: 2, keywords: [], tribes: ['mech'], effects: [{ trigger: 'triple', target: 'friendly', tribe: 'mech', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-deflector', name: L('Сварщик-отражатель', 'Deflector Welder'), description: L('Когда другой ваш механизм теряет щит: +1/+1.', 'Whenever another friendly mech loses Divine Shield: +1/+1.'), tavernTier: 2, attack: 3, health: 2, keywords: ['divineShield'], tribes: ['mech'], effects: [{ trigger: 'shieldPop', onTribe: 'mech', target: 'self', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-gear-hoarder', name: L('Скопидом-слесарь', 'Gear Hoarder'), description: L('После обновления лавки: механизмы в руке получают +1/+1.', 'After you refresh the tavern: mechs in your hand get +1/+1.'), tavernTier: 2, attack: 2, health: 2, keywords: [], tribes: ['mech'], effects: [{ trigger: 'reroll', target: 'hand', tribe: 'mech', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-assembler', name: L('Сборщик', 'Assembler'), description: L('Когда ваш механизм призван в бою: +1/+1.', 'Whenever a friendly mech is summoned in combat: +1/+1.'), tavernTier: 2, attack: 2, health: 3, keywords: [], tribes: ['mech'], effects: [{ trigger: 'friendlySummon', onTribe: 'mech', target: 'self', action: { kind: 'buff', attack: 1, health: 1 } }] },
  // Pirates
  { id: 'ab-pickpocket', name: L('Карманник', 'Pickpocket'), description: L('Продаётся за 3 доллара.', 'Sells for $3.'), tavernTier: 2, attack: 2, health: 2, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'sell', action: { kind: 'gold', amount: 2 } }] },
  { id: 'ab-freebooter', name: L('Флибустьер', 'Freebooter'), description: L('После обновления лавки: другие ваши пираты получают +1 к атаке.', 'After you refresh the tavern: your other pirates get +1 Attack.'), tavernTier: 2, attack: 2, health: 3, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'reroll', target: 'friendly', tribe: 'pirate', action: { kind: 'buff', attack: 1, health: 0 } }] },
  { id: 'ab-first-mate', name: L('Старпом', 'First Mate'), description: L('После покупки пирата: он получает +1/+1.', 'After you buy a pirate, give it +1/+1.'), tavernTier: 2, attack: 3, health: 2, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'buy', onTribe: 'pirate', target: 'bought', action: { kind: 'buff', attack: 1, health: 1 } }] },
  // Undead
  { id: 'ab-skeleton', name: L('Скелет', 'Skeleton'), tavernTier: 2, attack: 2, health: 2, keywords: ['reborn'], tribes: ['undead'] },
  { id: 'ab-gravedigger', name: L('Могильщик', 'Gravedigger'), description: L('Предсмертный хрип: случайная ваша нежить получает +2/+2.', 'Deathrattle: a random friendly undead gets +2/+2.'), tavernTier: 2, attack: 2, health: 3, keywords: ['deathrattle'], tribes: ['undead'], effects: [{ trigger: 'deathrattle', target: 'random', tribe: 'undead', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-necro-apprentice', name: L('Ученик некроманта', 'Necro Apprentice'), description: L('После продажи нежити: другая ваша нежить получает +1/+1.', 'After you sell an undead: your other undead get +1/+1.'), tavernTier: 2, attack: 2, health: 2, keywords: [], tribes: ['undead'], effects: [{ trigger: 'sell', onTribe: 'undead', target: 'friendly', tribe: 'undead', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-wraith', name: L('Призрак', 'Wraith'), description: L('Когда ваше существо с возрождением погибает: +1/+1.', 'Whenever a friendly Reborn minion dies: +1/+1.'), tavernTier: 2, attack: 3, health: 1, keywords: ['reborn'], tribes: ['undead'], effects: [{ trigger: 'friendlyDeath', onKeyword: 'reborn', target: 'self', action: { kind: 'buff', attack: 1, health: 1 } }] },
  // Dragons
  { id: 'ab-bronze-warden', name: L('Бронзовый страж', 'Bronze Warden'), tavernTier: 2, attack: 2, health: 1, keywords: ['divineShield', 'reborn'], tribes: ['dragon'] },
  { id: 'ab-glyph-guardian', name: L('Хранитель глифов', 'Glyph Guardian'), description: L('После атаки другого вашего дракона: он получает +1 к атаке.', 'After another friendly dragon attacks, give it +1 Attack.'), tavernTier: 2, attack: 2, health: 4, keywords: [], tribes: ['dragon'], effects: [{ trigger: 'friendlyAttack', onTribe: 'dragon', target: 'subject', action: { kind: 'buff', attack: 1, health: 0 } }] },
  { id: 'ab-dragon-egg', name: L('Драконье яйцо', 'Dragon Egg'), description: L('Предсмертный хрип: призывает Дракончика 2/2. Не атакует.', 'Deathrattle: summon a 2/2 Drake. Cannot attack.'), tavernTier: 2, attack: 0, health: 2, keywords: ['cannotAttack', 'deathrattle'], tribes: ['dragon'], deathrattle: { summonId: 'ab-token-drake', count: 1 } },
  // Demons
  { id: 'ab-soul-warden', name: L('Хранитель души', 'Soul Warden'), description: L('Ваш герой не получает урона от ваших демонов.', 'Your hero takes no damage from your demons.'), tavernTier: 2, attack: 2, health: 4, keywords: ['taunt'], tribes: ['demon'], effects: [{ trigger: 'aura', action: { kind: 'guard' } }] },
  { id: 'ab-blood-imp', name: L('Кровавый бес', 'Blood Imp'), description: L('Боевой клич: ваш герой получает 2 урона. Другие ваши демоны получают +1/+1.', 'Battlecry: your hero takes 2 damage. Your other demons get +1/+1.'), tavernTier: 2, attack: 3, health: 2, keywords: ['battlecry'], tribes: ['demon'], effects: [{ trigger: 'battlecry', action: { kind: 'selfDamage', amount: 2 }, steps: [{ target: 'friendly', tribe: 'demon', action: { kind: 'buff', attack: 1, health: 1 } }] }] },
  { id: 'ab-feeder', name: L('Кормилец', 'Feeder'), description: L('После пожирания существа из лавки: существа в лавке получают +1/+1.', 'After a friendly minion devours: tavern minions get +1/+1.'), tavernTier: 2, attack: 2, health: 3, keywords: [], tribes: ['demon'], effects: [{ trigger: 'devour', target: 'tavern', tribe: 'all', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-imp-trainer', name: L('Дрессировщик бесов', 'Imp Trainer'), description: L('После розыгрыша демона: он получает +1/+1.', 'After you play a demon, give it +1/+1.'), tavernTier: 2, attack: 2, health: 2, keywords: [], tribes: ['demon'], effects: [{ trigger: 'play', onTribe: 'demon', target: 'subject', action: { kind: 'buff', attack: 1, health: 1 } }] },
  // Neutrals
  { id: 'ab-bruiser', name: L('Громила', 'Bruiser'), tavernTier: 2, attack: 3, health: 3, keywords: [], tribes: ['neutral'] },
  { id: 'ab-bouncer', name: L('Вышибала', 'Bouncer'), tavernTier: 2, attack: 3, health: 2, keywords: ['taunt'], tribes: ['neutral'] },
  { id: 'ab-selfless', name: L('Самоотверженный герой', 'Selfless Champion'), description: L('Предсмертный хрип: случайное ваше существо получает щит.', 'Deathrattle: a random friendly minion gains Divine Shield.'), tavernTier: 2, attack: 2, health: 1, keywords: ['deathrattle'], tribes: ['neutral'], effects: [{ trigger: 'deathrattle', target: 'random', tribe: 'all', action: { kind: 'keyword', keyword: 'divineShield' } }] },
  { id: 'ab-carousel', name: L('Ярмарочная карусель', 'Fairground Carousel'), description: L('В конце хода: другое случайное ваше существо получает +1/+1 за каждый тип существ на столе.', 'End of turn: another random friendly minion gets +1/+1 for each minion type on your board.'), tavernTier: 2, attack: 2, health: 3, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'endTurn', target: 'random', tribe: 'all', per: 'tribes', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-lookout', name: L('Дозорный с вышки', 'Tower Lookout'), description: L('В конце хода: существа в руке получают +1 к атаке.', 'End of turn: minions in your hand get +1 Attack.'), tavernTier: 2, attack: 2, health: 3, keywords: ['taunt'], tribes: ['neutral'], effects: [{ trigger: 'endTurn', target: 'hand', tribe: 'all', action: { kind: 'buff', attack: 1, health: 0 } }] },
  { id: 'ab-bottler', name: L('Разливщица зелий', 'Potion Bottler'), description: L('Боевой клич: случайный ваш зверь получает яд.', 'Battlecry: a random friendly beast gains Poisonous.'), tavernTier: 2, attack: 2, health: 2, keywords: ['battlecry'], tribes: ['neutral'], effects: [{ trigger: 'battlecry', target: 'random', tribe: 'beast', action: { kind: 'keyword', keyword: 'poisonous' } }] },
  { id: 'ab-spellbinder', name: L('Ярмарочный заклинатель', 'Fair Spellbinder'), description: L('После заклинания таверны: соседи получают +1/+1.', 'After you play a tavern spell: adjacent minions get +1/+1.'), tavernTier: 2, attack: 2, health: 3, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'spell', target: 'adjacent', action: { kind: 'buff', attack: 1, health: 1 } }] },

  // ══════════════════════════════ Tier 3 ══════════════════════════════
  // Beasts
  { id: 'ab-fang', name: L('Клык', 'Fang'), tavernTier: 3, attack: 3, health: 2, keywords: ['poisonous'], tribes: ['beast'] },
  { id: 'ab-houndmaster', name: L('Псарь', 'Houndmaster'), description: L('Боевой клич: другой случайный ваш зверь получает +2/+2.', 'Battlecry: another random friendly beast gets +2/+2.'), tavernTier: 3, attack: 3, health: 3, keywords: ['battlecry'], tribes: ['beast'], effects: [{ trigger: 'battlecry', target: 'random', tribe: 'beast', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-rat-king', name: L('Крысиный король', 'Rat King'), description: L('Когда ваш зверь погибает: другие ваши звери получают +1 к атаке.', 'Whenever a friendly beast dies: your other beasts get +1 Attack.'), tavernTier: 3, attack: 2, health: 4, keywords: [], tribes: ['beast'], effects: [{ trigger: 'friendlyDeath', onTribe: 'beast', target: 'friendly', tribe: 'beast', action: { kind: 'buff', attack: 1, health: 0 } }] },
  { id: 'ab-poison-frog', name: L('Ядовитая жаба', 'Poison Frog'), tavernTier: 3, attack: 1, health: 1, keywords: ['poisonous', 'divineShield'], tribes: ['beast'] },
  { id: 'ab-warren', name: L('Кроличья нора', 'Rabbit Warren'), description: L('Когда ваш зверь призван в бою: он получает +2/+1.', 'Whenever a friendly beast is summoned in combat, give it +2/+1.'), tavernTier: 3, attack: 2, health: 4, keywords: [], tribes: ['beast'], effects: [{ trigger: 'friendlySummon', onTribe: 'beast', target: 'subject', action: { kind: 'buff', attack: 2, health: 1 } }] },
  // Mechs
  { id: 'ab-bulwark', name: L('Бастион', 'Bulwark'), tavernTier: 3, attack: 3, health: 5, keywords: ['taunt'], tribes: ['mech'] },
  { id: 'ab-welder', name: L('Сварщик', 'Welder'), description: L('После покупки механизма: он получает +2/+1.', 'After you buy a mech, give it +2/+1.'), tavernTier: 3, attack: 2, health: 4, keywords: [], tribes: ['mech'], effects: [{ trigger: 'buy', onTribe: 'mech', target: 'bought', action: { kind: 'buff', attack: 2, health: 1 } }] },
  { id: 'ab-module', name: L('Модуль сварщика', 'Welder Module'), description: L('После покупки механизма: он получает щит.', 'After you buy a mech, give it Divine Shield.'), tavernTier: 3, attack: 1, health: 3, keywords: ['taunt', 'divineShield'], tribes: ['mech'], effects: [{ trigger: 'buy', onTribe: 'mech', target: 'bought', action: { kind: 'keyword', keyword: 'divineShield' } }] },
  { id: 'ab-cobalt', name: L('Кобальтовый слесарь', 'Cobalt Locksmith'), description: L('Когда другое ваше существо теряет щит: другие ваши механизмы получают +1/+1.', 'Whenever another friendly minion loses Divine Shield: your other mechs get +1/+1.'), tavernTier: 3, attack: 3, health: 3, keywords: [], tribes: ['mech'], effects: [{ trigger: 'shieldPop', target: 'friendly', tribe: 'mech', action: { kind: 'buff', attack: 1, health: 1 } }] },
  // Pirates
  { id: 'ab-dervish', name: L('Дервиш', 'Dervish'), tavernTier: 3, attack: 2, health: 3, keywords: ['windfury'], tribes: ['pirate'] },
  { id: 'ab-smuggler', name: L('Контрабандист', 'Smuggler'), description: L('В конце хода: +1 доллар на следующий ход.', 'End of turn: +$1 next turn.'), tavernTier: 3, attack: 3, health: 3, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'endTurn', action: { kind: 'gold', amount: 1 } }] },
  { id: 'ab-drummer', name: L('Барабанщик', 'Drummer'), description: L('В конце хода: соседи получают +1/+1.', 'End of turn: adjacent minions get +1/+1.'), tavernTier: 3, attack: 2, health: 4, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'endTurn', target: 'adjacent', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-trader', name: L('Торгаш', 'Trader'), description: L('Боевой клич: +2 доллара.', 'Battlecry: gain $2.'), tavernTier: 3, attack: 3, health: 2, keywords: ['battlecry'], tribes: ['pirate'], effects: [{ trigger: 'battlecry', action: { kind: 'gold', amount: 2 } }] },
  { id: 'ab-southsea', name: L('Капитан Солёных вод', 'Saltwater Captain'), description: L('Другие ваши пираты получают +1 к атаке в бою.', 'Your other pirates have +1 Attack in combat.'), tavernTier: 3, attack: 3, health: 3, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'aura', tribe: 'pirate', action: { kind: 'aura', attack: 1 } }] },
  { id: 'ab-looter', name: L('Мародёр', 'Salty Looter'), description: L('После розыгрыша пирата: +1/+1.', 'After you play a pirate: +1/+1.'), tavernTier: 3, attack: 3, health: 3, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'play', onTribe: 'pirate', target: 'self', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-coin-flipper', name: L('Крутила', 'Coin Flipper'), description: L('После обновления лавки: +1/+1.', 'After you refresh the tavern: +1/+1.'), tavernTier: 3, attack: 2, health: 3, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'reroll', target: 'self', action: { kind: 'buff', attack: 1, health: 1 } }] },
  // Undead
  { id: 'ab-banshee', name: L('Банши', 'Banshee'), description: L('В начале боя: другая ваша нежить получает +1/+1.', 'Start of combat: your other undead get +1/+1.'), tavernTier: 3, attack: 3, health: 3, keywords: [], tribes: ['undead'], effects: [{ trigger: 'startCombat', target: 'friendly', tribe: 'undead', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-lich', name: L('Лич', 'Lich'), description: L('Предсмертный хрип: призывает двух Скелетов-слуг 2/1.', 'Deathrattle: summon two 2/1 Bone Servants.'), tavernTier: 3, attack: 3, health: 4, keywords: ['deathrattle'], tribes: ['undead'], deathrattle: { summonId: 'ab-token-skel', count: 2 } },
  { id: 'ab-crypt-lord', name: L('Владыка склепа', 'Crypt Lord'), description: L('Когда ваше существо погибает: +1/+1.', 'Whenever a friendly minion dies: +1/+1.'), tavernTier: 3, attack: 2, health: 5, keywords: ['taunt'], tribes: ['undead'], effects: [{ trigger: 'friendlyDeath', target: 'self', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-ghoul-pack', name: L('Стая гулей', 'Ghoul Pack'), description: L('Предсмертный хрип: призывает две Тени 1/1 с возрождением.', 'Deathrattle: summon two 1/1 Shades with Reborn.'), tavernTier: 3, attack: 3, health: 3, keywords: ['deathrattle'], tribes: ['undead'], deathrattle: { summonId: 'ab-token-shade', count: 2 } },
  // Dragons
  { id: 'ab-bronze-drake', name: L('Бронзовый дракон', 'Bronze Drake'), description: L('В начале боя: другие ваши драконы получают +1/+1.', 'Start of combat: your other dragons get +1/+1.'), tavernTier: 3, attack: 3, health: 4, keywords: [], tribes: ['dragon'], effects: [{ trigger: 'startCombat', target: 'friendly', tribe: 'dragon', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-hangry-dragon', name: L('Голодный дракон', 'Hangry Dragon'), description: L('После атаки другого вашего дракона: +1/+1.', 'After another friendly dragon attacks: +1/+1.'), tavernTier: 3, attack: 4, health: 4, keywords: [], tribes: ['dragon'], effects: [{ trigger: 'friendlyAttack', onTribe: 'dragon', target: 'self', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-dragon-herald', name: L('Драконий герольд', 'Dragon Herald'), description: L('После заклинания таверны: другие ваши драконы получают +1/+1.', 'After you play a tavern spell: your other dragons get +1/+1.'), tavernTier: 3, attack: 2, health: 4, keywords: [], tribes: ['dragon'], effects: [{ trigger: 'spell', target: 'friendly', tribe: 'dragon', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-whelp', name: L('Змееныш', 'Whelp'), tavernTier: 3, attack: 7, health: 6, keywords: [], tribes: ['beast'] },
  // Demons
  { id: 'ab-blood-seer', name: L('Кровавая ведунья', 'Blood Seer'), description: L('После урона герою от ваших демонов: другие ваши демоны получают +1/+1.', 'After your hero takes damage from your demons: your other demons get +1/+1.'), tavernTier: 3, attack: 2, health: 5, keywords: [], tribes: ['demon'], effects: [{ trigger: 'selfDamage', target: 'friendly', tribe: 'demon', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-imp-mother', name: L('Мать бесов', 'Imp Mother'), description: L('В конце хода: ваш герой получает 1 урон; призывает Бесёнка 1/1.', 'End of turn: your hero takes 1 damage; summon a 1/1 Imp.'), tavernTier: 3, attack: 3, health: 4, keywords: [], tribes: ['demon'], effects: [{ trigger: 'endTurn', action: { kind: 'selfDamage', amount: 1 }, steps: [{ action: { kind: 'summon', summonId: 'ab-token-imp', count: 1 } }] }] },
  { id: 'ab-ravenous', name: L('Ненасытный', 'Ravenous'), description: L('Боевой клич: пожирает два существа из лавки и получает их характеристики.', 'Battlecry: devour two tavern minions and gain their stats.'), tavernTier: 3, attack: 2, health: 2, keywords: ['battlecry'], tribes: ['demon'], effects: [{ trigger: 'battlecry', target: 'self', action: { kind: 'devour', count: 2 } }] },
  { id: 'ab-imp-chieftain', name: L('Атаман бесов', 'Imp Chieftain'), description: L('Боевой клич: другой случайный ваш демон получает +2/+2.', 'Battlecry: another random friendly demon gets +2/+2.'), tavernTier: 3, attack: 3, health: 3, keywords: ['battlecry'], tribes: ['demon'], effects: [{ trigger: 'battlecry', target: 'random', tribe: 'demon', action: { kind: 'buff', attack: 2, health: 2 } }] },
  // Neutrals
  { id: 'ab-collector', name: L('Коллекционер', 'Collector'), description: L('Триплет: +2/+2.', 'After you make a triple: +2/+2.'), tavernTier: 3, attack: 3, health: 3, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'triple', target: 'self', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-bard', name: L('Бродячий бард', 'Wandering Bard'), description: L('Боевой клич: соседи получают +1/+1 за каждый тип существ на столе.', 'Battlecry: adjacent minions get +1/+1 for each minion type on your board.'), tavernTier: 3, attack: 3, health: 3, keywords: ['battlecry'], tribes: ['neutral'], effects: [{ trigger: 'battlecry', target: 'adjacent', per: 'tribes', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-trainer', name: L('Тренер дворовой команды', 'Yard Coach'), description: L('После покупки существа: существа в руке получают +1 к атаке.', 'After you buy a minion: minions in your hand get +1 Attack.'), tavernTier: 3, attack: 2, health: 4, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'buy', target: 'hand', tribe: 'all', action: { kind: 'buff', attack: 1, health: 0 } }] },
  { id: 'ab-shieldbearer', name: L('Щитоносец гарнизона', 'Garrison Shieldbearer'), description: L('Когда другое ваше существо теряет щит: +2 к атаке.', 'Whenever another friendly minion loses Divine Shield: +2 Attack.'), tavernTier: 3, attack: 1, health: 6, keywords: ['taunt', 'divineShield'], tribes: ['neutral'], effects: [{ trigger: 'shieldPop', target: 'self', action: { kind: 'buff', attack: 2, health: 0 } }] },
  { id: 'ab-twin-blade', name: L('Двуручник с ярмарки', 'Fair Two-Hander'), tavernTier: 3, attack: 3, health: 3, keywords: ['windfury'], tribes: ['neutral'] },

  // ══════════════════════════════ Tier 4 ══════════════════════════════
  // Beasts
  { id: 'ab-howler', name: L('Ревун', 'Howler'), tavernTier: 4, attack: 4, health: 6, keywords: ['taunt'], tribes: ['beast'] },
  { id: 'ab-den-mother', name: L('Мать стаи', 'Den Mother'), description: L('В конце хода: другие ваши звери получают +1/+1.', 'End of turn: your other beasts get +1/+1.'), tavernTier: 4, attack: 4, health: 4, keywords: [], tribes: ['beast'], effects: [{ trigger: 'endTurn', target: 'friendly', tribe: 'beast', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-scavenger', name: L('Стервятник', 'Scavenger'), description: L('После продажи существа: другой случайный ваш зверь получает +2/+2.', 'After you sell a minion: another random friendly beast gets +2/+2.'), tavernTier: 4, attack: 4, health: 3, keywords: [], tribes: ['beast'], effects: [{ trigger: 'sell', target: 'random', tribe: 'beast', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-boar', name: L('Кабан-секач', 'Cleaver Boar'), tavernTier: 4, attack: 3, health: 5, keywords: ['cleave'], tribes: ['beast'] },
  { id: 'ab-hunter', name: L('Ловчий', 'Hunter'), description: L('После розыгрыша зверя: он получает +2/+2.', 'After you play a beast, give it +2/+2.'), tavernTier: 4, attack: 4, health: 3, keywords: [], tribes: ['beast'], effects: [{ trigger: 'play', onTribe: 'beast', target: 'subject', action: { kind: 'buff', attack: 2, health: 2 } }] },
  // Mechs
  { id: 'ab-knight', name: L('Рыцарь', 'Knight'), tavernTier: 4, attack: 4, health: 5, keywords: ['divineShield'], tribes: ['mech'] },
  { id: 'ab-forgemaster', name: L('Кузнец', 'Forgemaster'), description: L('Боевой клич: другие ваши механизмы получают +2/+1.', 'Battlecry: your other mechs get +2/+1.'), tavernTier: 4, attack: 3, health: 5, keywords: ['battlecry'], tribes: ['mech'], effects: [{ trigger: 'battlecry', target: 'friendly', tribe: 'mech', action: { kind: 'buff', attack: 2, health: 1 } }] },
  { id: 'ab-rover', name: L('Патрульный сварщик', 'Security Welder'), description: L('Предсмертный хрип: призывает трёх Учеников сварщика 1/1.', 'Deathrattle: summon three 1/1 Welder Apprentices.'), tavernTier: 4, attack: 2, health: 6, keywords: ['taunt', 'deathrattle'], tribes: ['mech'], deathrattle: { summonId: 'ab-token-microbot', count: 3 } },
  { id: 'ab-holy-mech', name: L('Святой сварщик', 'Holy Welder'), description: L('В начале боя: другой случайный ваш механизм получает щит.', 'Start of combat: another random friendly mech gains Divine Shield.'), tavernTier: 4, attack: 4, health: 4, keywords: ['divineShield'], tribes: ['mech'], effects: [{ trigger: 'startCombat', target: 'random', tribe: 'mech', action: { kind: 'keyword', keyword: 'divineShield' } }] },
  { id: 'ab-foundry', name: L('Литейщик', 'Foundry Hand'), description: L('В конце хода: призывает Ученика сварщика 1/1.', 'End of turn: summon a 1/1 Welder Apprentice.'), tavernTier: 4, attack: 3, health: 5, keywords: [], tribes: ['mech'], effects: [{ trigger: 'endTurn', action: { kind: 'summon', summonId: 'ab-token-microbot', count: 1 } }] },
  // Pirates
  { id: 'ab-hook', name: L('Крюк', 'Hook'), description: L('После покупки пирата: +2/+1.', 'After you buy a pirate: +2/+1.'), tavernTier: 4, attack: 4, health: 3, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'buy', onTribe: 'pirate', target: 'self', action: { kind: 'buff', attack: 2, health: 1 } }] },
  { id: 'ab-cannoneer', name: L('Канонир', 'Cannoneer'), description: L('В начале боя: +3 к атаке.', 'Start of combat: +3 Attack.'), tavernTier: 4, attack: 5, health: 3, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'startCombat', target: 'self', action: { kind: 'buff', attack: 3, health: 0 } }] },
  { id: 'ab-ripsnarl', name: L('Капитан Рваный Парус', 'Captain Tornsail'), description: L('После атаки другого вашего пирата: другие ваши пираты получают +1 к атаке.', 'After another friendly pirate attacks: your other pirates get +1 Attack.'), tavernTier: 4, attack: 4, health: 5, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'friendlyAttack', onTribe: 'pirate', target: 'friendly', tribe: 'pirate', action: { kind: 'buff', attack: 1, health: 0 } }] },
  { id: 'ab-bosun', name: L('Боцман', 'Bosun'), description: L('После обновления лавки: другие ваши пираты получают +1/+1.', 'After you refresh the tavern: your other pirates get +1/+1.'), tavernTier: 4, attack: 3, health: 5, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'reroll', target: 'friendly', tribe: 'pirate', action: { kind: 'buff', attack: 1, health: 1 } }] },
  // Undead
  { id: 'ab-butcher', name: L('Мясник', 'Butcher'), tavernTier: 4, attack: 4, health: 3, keywords: ['cleave'], tribes: ['undead'] },
  { id: 'ab-revenant', name: L('Ревенант', 'Revenant'), description: L('Предсмертный хрип: случайная ваша нежить получает +3/+3.', 'Deathrattle: a random friendly undead gets +3/+3.'), tavernTier: 4, attack: 4, health: 4, keywords: ['reborn', 'deathrattle'], tribes: ['undead'], effects: [{ trigger: 'deathrattle', target: 'random', tribe: 'undead', action: { kind: 'buff', attack: 3, health: 3 } }] },
  { id: 'ab-dark-priestess', name: L('Тёмная жрица', 'Dark Priestess'), description: L('Когда ваша нежить погибает: другая ваша нежить получает +1/+1.', 'Whenever a friendly undead dies: your other undead get +1/+1.'), tavernTier: 4, attack: 4, health: 4, keywords: [], tribes: ['undead'], effects: [{ trigger: 'friendlyDeath', onTribe: 'undead', target: 'friendly', tribe: 'undead', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-bone-baron', name: L('Костяной барон', 'Bone Baron'), description: L('Боевой клич: другая случайная ваша нежить получает возрождение.', 'Battlecry: another random friendly undead gains Reborn.'), tavernTier: 4, attack: 3, health: 5, keywords: ['battlecry'], tribes: ['undead'], effects: [{ trigger: 'battlecry', target: 'random', tribe: 'undead', action: { kind: 'keyword', keyword: 'reborn' } }] },
  // Dragons
  { id: 'ab-drakonid', name: L('Драконид-каратель', 'Drakonid Enforcer'), description: L('Когда другое ваше существо теряет щит: +2/+2.', 'Whenever another friendly minion loses Divine Shield: +2/+2.'), tavernTier: 4, attack: 3, health: 6, keywords: [], tribes: ['dragon'], effects: [{ trigger: 'shieldPop', target: 'self', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-twilight-drake', name: L('Сумеречный дракон', 'Twilight Drake'), description: L('В начале боя: +1/+1 за каждого вашего дракона.', 'Start of combat: +1/+1 for each friendly dragon.'), tavernTier: 4, attack: 4, health: 4, keywords: [], tribes: ['dragon'], effects: [{ trigger: 'startCombat', target: 'self', per: 'minions', perTribe: 'dragon', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-whelp-mother', name: L('Мать драконят', 'Whelp Mother'), description: L('Предсмертный хрип: призывает двух Дракончиков 2/2.', 'Deathrattle: summon two 2/2 Drakes.'), tavernTier: 4, attack: 3, health: 5, keywords: ['deathrattle'], tribes: ['dragon'], deathrattle: { summonId: 'ab-token-drake', count: 2 } },
  // Demons
  { id: 'ab-devourer', name: L('Демон-дракон «Пожиратель»', 'Demon-Dragon Devourer'), description: L('Боевой клич: пожирает три существа из лавки и получает их характеристики. Демон и дракон.', 'Battlecry: devour three tavern minions and gain their stats. Demon and dragon.'), tavernTier: 4, attack: 3, health: 3, keywords: ['battlecry'], tribes: ['demon', 'dragon'], effects: [{ trigger: 'battlecry', target: 'self', action: { kind: 'devour', count: 3 } }] },
  { id: 'ab-blood-champion', name: L('Чемпион крови', 'Blood Champion'), description: L('После урона герою от ваших демонов: +2/+2.', 'After your hero takes damage from your demons: +2/+2.'), tavernTier: 4, attack: 4, health: 5, keywords: [], tribes: ['demon'], effects: [{ trigger: 'selfDamage', target: 'self', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-fel-lord', name: L('Повелитель бесов', 'Fel Lord'), description: L('В конце хода: другие ваши демоны получают +1/+1.', 'End of turn: your other demons get +1/+1.'), tavernTier: 4, attack: 4, health: 4, keywords: [], tribes: ['demon'], effects: [{ trigger: 'endTurn', target: 'friendly', tribe: 'demon', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-glutton-butcher', name: L('Ненасытный мясник', 'Ravenous Butcher'), description: L('После пожирания существа из лавки: +2/+2.', 'After a friendly minion devours: +2/+2.'), tavernTier: 4, attack: 3, health: 6, keywords: [], tribes: ['demon'], effects: [{ trigger: 'devour', target: 'self', action: { kind: 'buff', attack: 2, health: 2 } }] },
  // Neutrals
  { id: 'ab-warlord', name: L('Полководец', 'Warlord'), description: L('Другие ваши существа получают +1 к атаке в бою.', 'Your other minions have +1 Attack in combat.'), tavernTier: 4, attack: 3, health: 5, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'aura', tribe: 'all', action: { kind: 'aura', attack: 1 } }] },
  { id: 'ab-barker', name: L('Ярмарочный зазывала', 'Fairground Barker'), description: L('В конце хода: +1/+1 за каждый тип существ на столе.', 'End of turn: +1/+1 for each minion type on your board.'), tavernTier: 4, attack: 2, health: 2, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'endTurn', target: 'self', per: 'tribes', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-magician', name: L('Фокусник-иллюзионист', 'Stage Magician'), description: L('Боевой клич: другое случайное ваше существо получает +2/+2 за каждый тип существ на столе.', 'Battlecry: another random friendly minion gets +2/+2 for each minion type on your board.'), tavernTier: 4, attack: 4, health: 4, keywords: ['battlecry'], tribes: ['neutral'], effects: [{ trigger: 'battlecry', target: 'random', tribe: 'all', per: 'tribes', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-mentor', name: L('Старый наставник', 'Old Mentor'), description: L('В конце хода: существа в руке получают +2/+2.', 'End of turn: minions in your hand get +2/+2.'), tavernTier: 5, attack: 3, health: 5, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'endTurn', target: 'hand', tribe: 'all', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-poisoner', name: L('Отравитель из подворотни', 'Alley Poisoner'), description: L('Боевой клич: другое случайное ваше существо получает яд.', 'Battlecry: another random friendly minion gains Poisonous.'), tavernTier: 4, attack: 3, health: 3, keywords: ['battlecry'], tribes: ['neutral'], effects: [{ trigger: 'battlecry', target: 'random', tribe: 'all', action: { kind: 'keyword', keyword: 'poisonous' } }] },
  { id: 'ab-windcaller', name: L('Заклинательница ветров', 'Windcaller'), description: L('Боевой клич: другое случайное ваше существо получает двойной удар.', 'Battlecry: another random friendly minion gains Windfury.'), tavernTier: 4, attack: 4, health: 3, keywords: ['battlecry'], tribes: ['neutral'], effects: [{ trigger: 'battlecry', target: 'random', tribe: 'all', action: { kind: 'keyword', keyword: 'windfury' } }] },
  { id: 'ab-bookkeeper', name: L('Счетовод', 'Bookkeeper'), description: L('После заклинания таверны: +1 доллар.', 'After you play a tavern spell: gain $1.'), tavernTier: 4, attack: 3, health: 4, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'spell', action: { kind: 'gold', amount: 1 } }] },

  // ══════════════════════════════ Tier 5 ══════════════════════════════
  // Beasts
  { id: 'ab-hydra', name: L('Гидра', 'Hydra'), description: L('Предсмертный хрип: призывает двух Кабанов-хищников 3/2.', 'Deathrattle: summon two 3/2 Boar Raptors.'), tavernTier: 5, attack: 3, health: 8, keywords: ['deathrattle'], tribes: ['beast'], deathrattle: { summonId: 'ab-token-raptor', count: 2 } },
  { id: 'ab-mama-bear', name: L('Медведица-великанша', 'Giant Mama Bear'), description: L('После розыгрыша зверя: он получает +4/+4.', 'After you play a beast, give it +4/+4.'), tavernTier: 5, attack: 5, health: 5, keywords: [], tribes: ['beast'], effects: [{ trigger: 'play', onTribe: 'beast', target: 'subject', action: { kind: 'buff', attack: 4, health: 4 } }] },
  { id: 'ab-primal', name: L('Первозверь', 'Primal Beast'), description: L('Боевой клич: другие ваши звери получают +2/+2.', 'Battlecry: your other beasts get +2/+2.'), tavernTier: 5, attack: 6, health: 6, keywords: ['battlecry'], tribes: ['beast'], effects: [{ trigger: 'battlecry', target: 'friendly', tribe: 'beast', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-poison-master', name: L('Отравительница', 'Poison Mistress'), description: L('В конце хода: другой случайный ваш зверь получает яд.', 'End of turn: another random friendly beast gains Poisonous.'), tavernTier: 5, attack: 4, health: 4, keywords: ['poisonous'], tribes: ['beast'], effects: [{ trigger: 'endTurn', target: 'random', tribe: 'beast', action: { kind: 'keyword', keyword: 'poisonous' } }] },
  // Mechs
  { id: 'ab-magnetron', name: L('Магнетрон', 'Magnetron'), description: L('После покупки механизма: +2/+2.', 'After you buy a mech: +2/+2.'), tavernTier: 5, attack: 5, health: 5, keywords: ['divineShield'], tribes: ['mech'], effects: [{ trigger: 'buy', onTribe: 'mech', target: 'self', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-junkbot', name: L('Петрович-исполин', 'Petrovich the Giant'), description: L('Когда ваш механизм погибает: +2/+2.', 'Whenever a friendly mech dies: +2/+2.'), tavernTier: 5, attack: 4, health: 6, keywords: [], tribes: ['mech'], effects: [{ trigger: 'friendlyDeath', onTribe: 'mech', target: 'self', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-shield-chain', name: L('Сварная цепь', 'Welded Chain'), description: L('Когда другое ваше существо теряет щит: другой случайный ваш механизм получает щит.', 'Whenever another friendly minion loses Divine Shield: another random friendly mech gains Divine Shield.'), tavernTier: 5, attack: 4, health: 6, keywords: ['divineShield'], tribes: ['mech'], effects: [{ trigger: 'shieldPop', target: 'random', tribe: 'mech', action: { kind: 'keyword', keyword: 'divineShield' } }] },
  // Pirates
  { id: 'ab-assassin', name: L('Убийца', 'Assassin'), tavernTier: 5, attack: 6, health: 5, keywords: ['poisonous'], tribes: ['pirate'] },
  { id: 'ab-admiral', name: L('Адмирал', 'Admiral'), description: L('В конце хода: другие ваши пираты получают +2/+1.', 'End of turn: your other pirates get +2/+1.'), tavernTier: 5, attack: 5, health: 5, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'endTurn', target: 'friendly', tribe: 'pirate', action: { kind: 'buff', attack: 2, health: 1 } }] },
  { id: 'ab-hoggarr', name: L('Капитан Золотой Зуб', 'Captain Goldtooth'), description: L('После покупки пирата: +1 доллар.', 'After you buy a pirate: gain $1.'), tavernTier: 5, attack: 5, health: 5, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'buy', onTribe: 'pirate', action: { kind: 'gold', amount: 1 } }] },
  { id: 'ab-corsair-queen', name: L('Королева корсаров', 'Corsair Queen'), description: L('После атаки другого вашего пирата: он получает +2/+2.', 'After another friendly pirate attacks, give it +2/+2.'), tavernTier: 5, attack: 5, health: 5, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'friendlyAttack', onTribe: 'pirate', target: 'subject', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-navigator', name: L('Штурман', 'Navigator'), description: L('После заклинания таверны: другие ваши пираты получают +1/+1.', 'After you play a tavern spell: your other pirates get +1/+1.'), tavernTier: 5, attack: 4, health: 6, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'spell', target: 'friendly', tribe: 'pirate', action: { kind: 'buff', attack: 1, health: 1 } }] },
  // Undead
  { id: 'ab-ashes', name: L('Пепел', 'Ashes'), tavernTier: 5, attack: 5, health: 4, keywords: ['reborn', 'windfury'], tribes: ['undead'] },
  { id: 'ab-grave-titan', name: L('Могильный титан', 'Grave Titan'), description: L('Когда ваше существо погибает: призывает Скелета-слугу 2/1.', 'Whenever a friendly minion dies: summon a 2/1 Bone Servant.'), tavernTier: 5, attack: 6, health: 6, keywords: [], tribes: ['undead'], effects: [{ trigger: 'friendlyDeath', action: { kind: 'summon', summonId: 'ab-token-skel', count: 1 } }] },
  { id: 'ab-bone-king', name: L('Костяной король', 'Bone King'), description: L('Предсмертный хрип: ваша нежить получает +3/+3.', 'Deathrattle: your undead get +3/+3.'), tavernTier: 5, attack: 5, health: 6, keywords: ['deathrattle'], tribes: ['undead'], effects: [{ trigger: 'deathrattle', target: 'friendly', tribe: 'undead', action: { kind: 'buff', attack: 3, health: 3 } }] },
  { id: 'ab-grave-echo', name: L('Могильное эхо', 'Grave Echo'), description: L('Предсмертные хрипы ваших существ срабатывают дважды.', "Your minions' Deathrattles trigger twice."), tavernTier: 5, attack: 3, health: 6, keywords: [], tribes: ['undead'], effects: [{ trigger: 'aura', action: { kind: 'echo', echo: 'deathrattle' } }] },
  // Dragons
  { id: 'ab-razorgore', name: L('Огнечешуй', 'Cinderscale'), description: L('В конце хода: +1/+1 за каждого вашего дракона.', 'End of turn: +1/+1 for each friendly dragon.'), tavernTier: 5, attack: 4, health: 6, keywords: [], tribes: ['dragon'], effects: [{ trigger: 'endTurn', target: 'self', per: 'minions', perTribe: 'dragon', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-aspect', name: L('Аспект магии', 'Aspect of Magic'), description: L('После розыгрыша существа с боевым кличем: другие ваши драконы получают +1/+1.', 'After you play a Battlecry minion: your other dragons get +1/+1.'), tavernTier: 5, attack: 4, health: 10, keywords: [], tribes: ['dragon'], effects: [{ trigger: 'play', onKeyword: 'battlecry', target: 'friendly', tribe: 'dragon', action: { kind: 'buff', attack: 1, health: 1 } }] },
  // Demons
  { id: 'ab-pain-priest', name: L('Жрец боли', 'Pain Priest'), description: L('Боевой клич: ваш герой получает 3 урона. Другие ваши демоны получают +3/+3.', 'Battlecry: your hero takes 3 damage. Your other demons get +3/+3.'), tavernTier: 5, attack: 3, health: 5, keywords: ['battlecry'], tribes: ['demon'], effects: [{ trigger: 'battlecry', action: { kind: 'selfDamage', amount: 3 }, steps: [{ target: 'friendly', tribe: 'demon', action: { kind: 'buff', attack: 3, health: 3 } }] }] },
  { id: 'ab-imp-matriarch', name: L('Матриарх бесов', 'Imp Matriarch'), description: L('После розыгрыша демона: он получает +3/+3.', 'After you play a demon, give it +3/+3.'), tavernTier: 5, attack: 5, health: 5, keywords: [], tribes: ['demon'], effects: [{ trigger: 'play', onTribe: 'demon', target: 'subject', action: { kind: 'buff', attack: 3, health: 3 } }] },
  { id: 'ab-gourmand', name: L('Гурман', 'Gourmand'), description: L('В конце хода: пожирает существо из лавки и получает его характеристики.', 'End of turn: devour a tavern minion and gain its stats.'), tavernTier: 5, attack: 4, health: 8, keywords: [], tribes: ['demon'], effects: [{ trigger: 'endTurn', target: 'self', action: { kind: 'devour', count: 1 } }] },
  // Neutrals
  { id: 'ab-golem', name: L('Голем', 'Golem'), tavernTier: 5, attack: 7, health: 7, keywords: ['taunt'], tribes: ['neutral'] },
  { id: 'ab-lightfang', name: L('Светоклык', 'Lightfang'), description: L('В конце хода: другое случайное ваше существо получает +2/+2 за каждый тип существ на столе.', 'End of turn: another random friendly minion gets +2/+2 for each minion type on your board.'), tavernTier: 5, attack: 2, health: 2, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'endTurn', target: 'random', tribe: 'all', per: 'tribes', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-ringmaster', name: L('Распорядитель цирка', 'Ringmaster'), description: L('Боевой клич: соседи получают +2/+2 за каждый тип существ на столе.', 'Battlecry: adjacent minions get +2/+2 for each minion type on your board.'), tavernTier: 5, attack: 5, health: 5, keywords: ['battlecry'], tribes: ['neutral'], effects: [{ trigger: 'battlecry', target: 'adjacent', per: 'tribes', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-hand-master', name: L('Хранитель кладовой', 'Pantry Keeper'), description: L('После покупки существа: существа в руке получают +1/+1.', 'After you buy a minion: minions in your hand get +1/+1.'), tavernTier: 5, attack: 5, health: 5, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'buy', target: 'hand', tribe: 'all', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-herald-echo', name: L('Глашатай Двух Голосов', 'Twice-Told Herald'), description: L('Ваши боевые кличи срабатывают дважды.', 'Your Battlecries trigger twice.'), tavernTier: 5, attack: 2, health: 5, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'aura', action: { kind: 'echo', echo: 'battlecry' } }] },
  { id: 'ab-marshal', name: L('Распорядитель призывов', "Summoner's Marshal"), description: L('Когда ваше существо призвано в бою: оно получает +2/+2.', 'Whenever a friendly minion is summoned in combat, give it +2/+2.'), tavernTier: 5, attack: 4, health: 5, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'friendlySummon', target: 'subject', action: { kind: 'buff', attack: 2, health: 2 } }] },

  // ══════════════════════════════ Tier 6 ══════════════════════════════
  // Beasts
  { id: 'ab-leviathan', name: L('Левиафан', 'Leviathan'), description: L('Предсмертный хрип: призывает двух Хряков-бугаев 3/3.', 'Deathrattle: summon two 3/3 Boar Brutes.'), tavernTier: 6, attack: 7, health: 9, keywords: ['deathrattle'], tribes: ['beast'], deathrattle: { summonId: 'ab-token-cub', count: 2 } },
  { id: 'ab-many-heads', name: L('Многоглавый хряк', 'Many-Headed Boar'), description: L('Предсмертный хрип: призывает двух Кабанов-хищников 3/2.', 'Deathrattle: summon two 3/2 Boar Raptors.'), tavernTier: 6, attack: 7, health: 7, keywords: ['deathrattle'], tribes: ['beast'], deathrattle: { summonId: 'ab-token-raptor', count: 2 } },
  { id: 'ab-goldrinn', name: L('Древний волк', 'Elder Wolf'), description: L('Предсмертный хрип: ваши звери получают +4/+4.', 'Deathrattle: your beasts get +4/+4.'), tavernTier: 6, attack: 4, health: 4, keywords: ['deathrattle'], tribes: ['beast'], effects: [{ trigger: 'deathrattle', target: 'friendly', tribe: 'beast', action: { kind: 'buff', attack: 4, health: 4 } }] },
  { id: 'ab-spider-queen', name: L('Паучиха-королева', 'Spider Queen'), tavernTier: 6, attack: 4, health: 9, keywords: ['poisonous', 'taunt'], tribes: ['beast'] },
  // Mechs
  { id: 'ab-colossus', name: L('Колосс', 'Colossus'), tavernTier: 6, attack: 8, health: 8, keywords: ['taunt', 'divineShield'], tribes: ['mech'] },
  { id: 'ab-reaper-4000', name: L('Жнец-4000 Петрович', 'Reaper 4000 Petrovich'), tavernTier: 6, attack: 6, health: 9, keywords: ['cleave'], tribes: ['mech'] },
  { id: 'ab-overclocker', name: L('Разгонщик', 'Overclocker'), description: L('В конце хода: другие ваши механизмы получают +2/+2.', 'End of turn: your other mechs get +2/+2.'), tavernTier: 6, attack: 5, health: 5, keywords: [], tribes: ['mech'], effects: [{ trigger: 'endTurn', target: 'friendly', tribe: 'mech', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-omega-shield', name: L('Омега-сварщик', 'Omega Welder'), description: L('Когда другое ваше существо теряет щит: другие ваши механизмы получают +2/+2.', 'Whenever another friendly minion loses Divine Shield: your other mechs get +2/+2.'), tavernTier: 6, attack: 6, health: 6, keywords: ['divineShield'], tribes: ['mech'], effects: [{ trigger: 'shieldPop', target: 'friendly', tribe: 'mech', action: { kind: 'buff', attack: 2, health: 2 } }] },
  // Pirates
  { id: 'ab-dreadnought', name: L('Дредноут', 'Dreadnought'), description: L('Боевой клич: другие ваши пираты получают +3/+3.', 'Battlecry: your other pirates get +3/+3.'), tavernTier: 6, attack: 5, health: 8, keywords: ['taunt', 'battlecry'], tribes: ['pirate'], effects: [{ trigger: 'battlecry', target: 'friendly', tribe: 'pirate', action: { kind: 'buff', attack: 3, health: 3 } }] },
  { id: 'ab-eliza', name: L('Королева пиратов', 'Pirate Queen'), description: L('После атаки другого вашего пирата: другие ваши существа получают +1/+1.', 'After another friendly pirate attacks: your other minions get +1/+1.'), tavernTier: 6, attack: 6, health: 7, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'friendlyAttack', onTribe: 'pirate', target: 'friendly', tribe: 'all', action: { kind: 'buff', attack: 1, health: 1 } }] },
  // Undead
  { id: 'ab-omen', name: L('Знамение', 'Omen'), tavernTier: 6, attack: 7, health: 8, keywords: ['taunt', 'divineShield'], tribes: ['undead'] },
  { id: 'ab-necropolis', name: L('Некрополь', 'Necropolis'), description: L('Предсмертный хрип: призывает трёх Скелетов-слуг 2/1.', 'Deathrattle: summon three 2/1 Bone Servants.'), tavernTier: 6, attack: 5, health: 9, keywords: ['reborn', 'deathrattle'], tribes: ['undead'], deathrattle: { summonId: 'ab-token-skel', count: 3 } },
  { id: 'ab-lord-of-bones', name: L('Повелитель костей', 'Lord of Bones'), description: L('Когда ваша нежить погибает: другая ваша нежить получает +2/+2.', 'Whenever a friendly undead dies: your other undead get +2/+2.'), tavernTier: 6, attack: 5, health: 9, keywords: ['reborn'], tribes: ['undead'], effects: [{ trigger: 'friendlyDeath', onTribe: 'undead', target: 'friendly', tribe: 'undead', action: { kind: 'buff', attack: 2, health: 2 } }] },
  // Dragons
  { id: 'ab-tarecgosa', name: L('Лазурная матриарх', 'Azure Matriarch'), description: L('После атаки другого вашего дракона: другие ваши драконы получают +1/+1.', 'After another friendly dragon attacks: your other dragons get +1/+1.'), tavernTier: 6, attack: 6, health: 8, keywords: [], tribes: ['dragon'], effects: [{ trigger: 'friendlyAttack', onTribe: 'dragon', target: 'friendly', tribe: 'dragon', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-nadina', name: L('Хранительница чешуи', 'Scale Warden'), description: L('Предсмертный хрип: ваши драконы получают щит.', 'Deathrattle: your dragons gain Divine Shield.'), tavernTier: 6, attack: 8, health: 5, keywords: ['deathrattle'], tribes: ['neutral'], effects: [{ trigger: 'deathrattle', target: 'friendly', tribe: 'dragon', action: { kind: 'keyword', keyword: 'divineShield' } }] },
  // Demons
  { id: 'ab-gargoyle', name: L('Горгулья', 'Gargoyle'), description: L('В конце хода: каждый другой ваш демон пожирает существо из лавки и получает его характеристики.', 'End of turn: each of your other demons devours a tavern minion and gains its stats.'), tavernTier: 6, attack: 5, health: 7, keywords: ['taunt'], tribes: ['demon'], effects: [{ trigger: 'endTurn', target: 'friendly', tribe: 'demon', action: { kind: 'devour', count: 1 } }] },
  { id: 'ab-blood-idol', name: L('Кровавый идол', 'Blood Idol'), description: L('После урона герою от ваших демонов: другие ваши демоны получают +2/+2.', 'After your hero takes damage from your demons: your other demons get +2/+2.'), tavernTier: 6, attack: 7, health: 7, keywords: [], tribes: ['demon'], effects: [{ trigger: 'selfDamage', target: 'friendly', tribe: 'demon', action: { kind: 'buff', attack: 2, health: 2 } }] },
  // Neutrals
  { id: 'ab-titan', name: L('Титан', 'Titan'), description: L('Триплет: +4/+4.', 'After you make a triple: +4/+4.'), tavernTier: 6, attack: 8, health: 8, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'triple', target: 'self', action: { kind: 'buff', attack: 4, health: 4 } }] },
  { id: 'ab-amalgam', name: L('Амальгама', 'Amalgam'), description: L('Боевой клич: +2/+2 за каждый тип существ на столе. Зверь, механизм и пират.', 'Battlecry: +2/+2 for each minion type on your board. Beast, mech and pirate.'), tavernTier: 6, attack: 6, health: 6, keywords: ['battlecry'], tribes: ['beast', 'mech', 'pirate'], effects: [{ trigger: 'battlecry', target: 'self', per: 'tribes', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-zoo-mogul', name: L('Хозяин зверинца', 'Menagerie Mogul'), description: L('В конце хода: другое случайное ваше существо получает +2/+2 за каждый тип существ на столе.', 'End of turn: another random friendly minion gets +2/+2 for each minion type on your board.'), tavernTier: 6, attack: 6, health: 6, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'endTurn', target: 'random', tribe: 'all', per: 'tribes', action: { kind: 'buff', attack: 2, health: 2 } }] },
];
