import type { AutoBattlerMinionDef } from './autoBattler';

type Loc = { ru: string; en: string };
const L = (ru: string, en: string): Loc => ({ ru, en });

/**
 * Starter tavern. Tribes keep one identity each: beasts breed tokens and hunt in packs,
 * mechs shield and stack armour, pirates chase gold and grow each turn, undead come back
 * and feed on their dead, neutrals are plain bodies with a few tavern-wide tricks.
 * Effects are data (see AutoBattlerEffect); the server interprets them.
 */
export const starterAutoBattlerMinions: AutoBattlerMinionDef[] = [
  // Tokens (never offered)
  { id: 'ab-token-1-1', name: L('Заводской Петрович', 'Factory Petrovich'), tavernTier: 1, attack: 1, health: 1, keywords: [], tribes: ['neutral'], token: true, inTavern: false, inDiscover: false },
  { id: 'ab-token-rat', name: L('Подсвинок', 'Piglet'), tavernTier: 1, attack: 1, health: 1, keywords: [], tribes: ['beast'], token: true, inTavern: false, inDiscover: false },
  { id: 'ab-token-skel', name: L('Скелет-слуга', 'Bone Servant'), tavernTier: 1, attack: 2, health: 1, keywords: [], tribes: ['undead'], token: true, inTavern: false, inDiscover: false },
  { id: 'ab-token-cub', name: L('Хряк-бугай', 'Boar Brute'), tavernTier: 3, attack: 3, health: 3, keywords: [], tribes: ['beast'], token: true, inTavern: false, inDiscover: false },

  // Spells (bought like minions, played from hand)
  { id: 'ab-discover', name: L('Открытие', 'Discover'), description: L('Выберите одно из трёх существ.', 'Discover one of three minions.'), tavernTier: 1, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'discover' }, generated: true, inTavern: false, inDiscover: false },
  { id: 'ab-spell-coin', name: L('Монета', 'Coin'), description: L('Получите 1 доллар.', 'Gain 1 gold.'), tavernTier: 1, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'coin', amount: 1 }, poolCopies: 8, inDiscover: false },
  { id: 'ab-spell-refresh', name: L('Свежая партия', 'Fresh Batch'), description: L('Следующее обновление лавки бесплатно.', 'Your next tavern refresh is free.'), tavernTier: 1, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'freeReroll', amount: 1 }, poolCopies: 8, inDiscover: false },
  { id: 'ab-spell-tonic', name: L('Настойка', 'Tonic'), description: L('Сыграйте на существо: +2/+2.', 'Play onto a minion: +2/+2.'), tavernTier: 2, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'tonic', amount: 2 }, poolCopies: 8, inDiscover: false },
  { id: 'ab-spell-deposit', name: L('Вклад', 'Deposit'), description: L('Получите 2 доллара.', 'Gain 2 gold.'), tavernTier: 3, attack: 0, health: 1, keywords: [], tribes: ['neutral'], spell: { kind: 'coin', amount: 2 }, poolCopies: 6, inDiscover: false },

  // ── Tier 1 ──
  { id: 'ab-whelp', name: L('Змееныш', 'Whelp'), tavernTier: 1, attack: 2, health: 1, keywords: [], tribes: ['beast'] },
  { id: 'ab-ward', name: L('Страж', 'Ward'), tavernTier: 1, attack: 1, health: 3, keywords: ['taunt'], tribes: ['mech'] },
  { id: 'ab-aegis', name: L('Эгида', 'Aegis'), tavernTier: 1, attack: 2, health: 2, keywords: ['divineShield'], tribes: ['mech'] },
  { id: 'ab-broker', name: L('Маклер', 'Broker'), description: L('Боевой клич: +1 доллар.', 'Battlecry: gain 1 gold.'), tavernTier: 1, attack: 1, health: 2, keywords: ['battlecry'], tribes: ['pirate'], battlecryId: 'ab-bc-gold', effects: [{ trigger: 'battlecry', action: { kind: 'gold', amount: 1 } }] },
  { id: 'ab-rat-pack', name: L('Крысиная стая', 'Rat Pack'), description: L('Предсмертный хрип: призывает Крысу 1/1.', 'Deathrattle: summon a 1/1 Rat.'), tavernTier: 1, attack: 1, health: 2, keywords: ['deathrattle'], tribes: ['beast'], deathrattle: { summonId: 'ab-token-rat', count: 1 } },
  { id: 'ab-scrap-bot', name: L('Хламобот', 'Scrap Bot'), description: L('Предсмертный хрип: призывает Жетон 1/1.', 'Deathrattle: summon a 1/1 Token.'), tavernTier: 1, attack: 1, health: 1, keywords: ['deathrattle'], tribes: ['mech'], deathrattle: { summonId: 'ab-token-1-1', count: 1 } },
  { id: 'ab-deckhand', name: L('Юнга', 'Deckhand'), description: L('В конце хода: +1 к атаке.', 'At the end of your turn: +1 attack.'), tavernTier: 1, attack: 2, health: 1, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'endTurn', target: 'self', action: { kind: 'buff', attack: 1, health: 0 } }] },
  { id: 'ab-ghoul', name: L('Гуль', 'Ghoul'), tavernTier: 1, attack: 1, health: 1, keywords: ['reborn'], tribes: ['undead'] },
  { id: 'ab-cub', name: L('Медвежонок', 'Cub'), description: L('Купили зверя — +1/+1.', 'After you buy a beast: +1/+1.'), tavernTier: 1, attack: 1, health: 1, keywords: [], tribes: ['beast'], effects: [{ trigger: 'buy', onTribe: 'beast', target: 'self', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-tinkerer', name: L('Жестянщик', 'Tinkerer'), description: L('Боевой клич: случайный ваш механизм получает +1/+1.', 'Battlecry: a random friendly mech gets +1/+1.'), tavernTier: 1, attack: 2, health: 1, keywords: ['battlecry'], tribes: ['mech'], effects: [{ trigger: 'battlecry', target: 'random', tribe: 'mech', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-swab', name: L('Швабра', 'Swab'), description: L('Продаётся за 2 доллара.', 'Sells for 2 gold.'), tavernTier: 1, attack: 1, health: 1, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'sell', action: { kind: 'gold', amount: 1 } }] },
  { id: 'ab-drunk', name: L('Пьянчуга', 'Drunk'), tavernTier: 1, attack: 2, health: 2, keywords: [], tribes: ['neutral'] },

  // ── Tier 2 ──
  { id: 'ab-viper', name: L('Гадюка', 'Viper'), tavernTier: 2, attack: 1, health: 2, keywords: ['poisonous'], tribes: ['beast'] },
  { id: 'ab-breeder', name: L('Заводчик', 'Breeder'), description: L('Предсмертный хрип: призывает Жетон 1/1.', 'Deathrattle: summon a 1/1 Token.'), tavernTier: 2, attack: 2, health: 2, keywords: ['deathrattle'], tribes: ['beast'], deathrattle: { summonId: 'ab-token-1-1', count: 1 } },
  { id: 'ab-bruiser', name: L('Громила', 'Bruiser'), tavernTier: 2, attack: 3, health: 3, keywords: [], tribes: ['neutral'] },
  { id: 'ab-alpha', name: L('Вожак', 'Alpha'), description: L('Другие ваши звери получают +2 к атаке в бою.', 'Your other beasts have +2 attack in combat.'), tavernTier: 2, attack: 2, health: 3, keywords: [], tribes: ['beast'], auraId: 'ab-aura-beasts', effects: [{ trigger: 'aura', tribe: 'beast', action: { kind: 'aura', attack: 2 } }] },
  { id: 'ab-shieldbot', name: L('Щитобот', 'Shieldbot'), description: L('Боевой клич: соседи получают +1/+1.', 'Battlecry: adjacent minions get +1/+1.'), tavernTier: 2, attack: 1, health: 3, keywords: ['taunt', 'battlecry'], tribes: ['mech'], effects: [{ trigger: 'battlecry', target: 'adjacent', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-parrot', name: L('Попугай', 'Parrot'), description: L('Сыграли зверя — +1/+1.', 'Whenever you play a beast: +1/+1.'), tavernTier: 2, attack: 2, health: 1, keywords: [], tribes: ['beast'], effects: [{ trigger: 'play', onTribe: 'beast', target: 'self', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-skeleton', name: L('Скелет', 'Skeleton'), tavernTier: 2, attack: 2, health: 2, keywords: ['reborn'], tribes: ['undead'] },
  { id: 'ab-gravedigger', name: L('Могильщик', 'Gravedigger'), description: L('Предсмертный хрип: случайная ваша нежить получает +2/+2.', 'Deathrattle: a random friendly undead gets +2/+2.'), tavernTier: 2, attack: 2, health: 3, keywords: ['deathrattle'], tribes: ['undead'], effects: [{ trigger: 'deathrattle', target: 'random', tribe: 'undead', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-mechanic', name: L('Механик', 'Mechanic'), description: L('Триплет: все ваши механизмы получают +1/+1.', 'Whenever you make a triple: your mechs get +1/+1.'), tavernTier: 2, attack: 2, health: 2, keywords: [], tribes: ['mech'], effects: [{ trigger: 'triple', target: 'friendly', tribe: 'mech', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-bouncer', name: L('Вышибала', 'Bouncer'), tavernTier: 2, attack: 3, health: 2, keywords: ['taunt'], tribes: ['neutral'] },
  { id: 'ab-pickpocket', name: L('Карманник', 'Pickpocket'), description: L('Продаётся за 3 доллара.', 'Sells for 3 gold.'), tavernTier: 2, attack: 2, health: 2, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'sell', action: { kind: 'gold', amount: 2 } }] },
  { id: 'ab-nest', name: L('Гнездо', 'Nest'), description: L('Предсмертный хрип: призывает двух Крыс 1/1.', 'Deathrattle: summon two 1/1 Rats.'), tavernTier: 2, attack: 1, health: 3, keywords: ['deathrattle'], tribes: ['beast'], deathrattle: { summonId: 'ab-token-rat', count: 2 } },

  // ── Tier 3 ──
  { id: 'ab-bulwark', name: L('Бастион', 'Bulwark'), tavernTier: 3, attack: 2, health: 5, keywords: ['taunt'], tribes: ['mech'] },
  { id: 'ab-fang', name: L('Клык', 'Fang'), tavernTier: 3, attack: 3, health: 2, keywords: ['poisonous'], tribes: ['beast'] },
  { id: 'ab-dervish', name: L('Дервиш', 'Dervish'), tavernTier: 3, attack: 2, health: 2, keywords: ['windfury'], tribes: ['pirate'] },
  { id: 'ab-smuggler', name: L('Контрабандист', 'Smuggler'), description: L('В конце хода: +1 доллар.', 'At the end of your turn: gain 1 gold.'), tavernTier: 3, attack: 3, health: 3, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'endTurn', action: { kind: 'gold', amount: 1 } }] },
  { id: 'ab-houndmaster', name: L('Псарь', 'Houndmaster'), description: L('Боевой клич: случайный ваш зверь получает +2/+2.', 'Battlecry: a random friendly beast gets +2/+2.'), tavernTier: 3, attack: 3, health: 3, keywords: ['battlecry'], tribes: ['beast'], effects: [{ trigger: 'battlecry', target: 'random', tribe: 'beast', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-welder', name: L('Сварщик', 'Welder'), description: L('Купленный механизм получает +1/+1.', 'After you buy a mech, it gets +1/+1.'), tavernTier: 3, attack: 2, health: 4, keywords: [], tribes: ['mech'], effects: [{ trigger: 'buy', onTribe: 'mech', target: 'bought', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-banshee', name: L('Банши', 'Banshee'), description: L('В начале боя: ваша нежить получает +1/+1.', 'Start of combat: your undead get +1/+1.'), tavernTier: 3, attack: 3, health: 3, keywords: [], tribes: ['undead'], effects: [{ trigger: 'startCombat', target: 'friendly', tribe: 'undead', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-drummer', name: L('Барабанщик', 'Drummer'), description: L('В конце хода: соседи получают +1/+1.', 'At the end of your turn: adjacent minions get +1/+1.'), tavernTier: 3, attack: 2, health: 4, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'endTurn', target: 'adjacent', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-lich', name: L('Лич', 'Lich'), description: L('Предсмертный хрип: призывает двух Скелетов-слуг 2/1.', 'Deathrattle: summon two 2/1 Bone Servants.'), tavernTier: 3, attack: 3, health: 4, keywords: ['deathrattle'], tribes: ['undead'], deathrattle: { summonId: 'ab-token-skel', count: 2 } },
  { id: 'ab-collector', name: L('Коллекционер', 'Collector'), description: L('Триплет: +2/+2.', 'Whenever you make a triple: +2/+2.'), tavernTier: 3, attack: 3, health: 3, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'triple', target: 'self', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-trader', name: L('Торгаш', 'Trader'), description: L('Боевой клич: +2 доллара.', 'Battlecry: gain 2 gold.'), tavernTier: 3, attack: 3, health: 2, keywords: ['battlecry'], tribes: ['pirate'], effects: [{ trigger: 'battlecry', action: { kind: 'gold', amount: 2 } }] },

  // ── Tier 4 ──
  { id: 'ab-knight', name: L('Рыцарь', 'Knight'), tavernTier: 4, attack: 4, health: 4, keywords: ['divineShield'], tribes: ['mech'] },
  { id: 'ab-howler', name: L('Ревун', 'Howler'), tavernTier: 4, attack: 3, health: 6, keywords: ['taunt'], tribes: ['beast'] },
  { id: 'ab-butcher', name: L('Мясник', 'Butcher'), tavernTier: 4, attack: 3, health: 3, keywords: ['cleave'], tribes: ['undead'] },
  { id: 'ab-den-mother', name: L('Мать стаи', 'Den Mother'), description: L('В конце хода: ваши звери получают +1/+1.', 'At the end of your turn: your beasts get +1/+1.'), tavernTier: 4, attack: 4, health: 4, keywords: [], tribes: ['beast'], effects: [{ trigger: 'endTurn', target: 'friendly', tribe: 'beast', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-forgemaster', name: L('Кузнец', 'Forgemaster'), description: L('Боевой клич: ваши механизмы получают +2/+1.', 'Battlecry: your mechs get +2/+1.'), tavernTier: 4, attack: 4, health: 5, keywords: ['battlecry'], tribes: ['mech'], effects: [{ trigger: 'battlecry', target: 'friendly', tribe: 'mech', action: { kind: 'buff', attack: 2, health: 1 } }] },
  { id: 'ab-hook', name: L('Крюк', 'Hook'), description: L('Купили пирата — +2/+1.', 'After you buy a pirate: +2/+1.'), tavernTier: 4, attack: 4, health: 3, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'buy', onTribe: 'pirate', target: 'self', action: { kind: 'buff', attack: 2, health: 1 } }] },
  { id: 'ab-revenant', name: L('Ревенант', 'Revenant'), description: L('Предсмертный хрип: случайная ваша нежить получает +3/+3.', 'Deathrattle: a random friendly undead gets +3/+3.'), tavernTier: 4, attack: 4, health: 4, keywords: ['reborn', 'deathrattle'], tribes: ['undead'], effects: [{ trigger: 'deathrattle', target: 'random', tribe: 'undead', action: { kind: 'buff', attack: 3, health: 3 } }] },
  { id: 'ab-warlord', name: L('Полководец', 'Warlord'), description: L('Другие ваши существа получают +1 к атаке в бою.', 'Your other minions have +1 attack in combat.'), tavernTier: 4, attack: 3, health: 5, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'aura', tribe: 'all', action: { kind: 'aura', attack: 1 } }] },
  { id: 'ab-scavenger', name: L('Стервятник', 'Scavenger'), description: L('Продали существо — случайный ваш зверь получает +2/+2.', 'Whenever you sell a minion: a random friendly beast gets +2/+2.'), tavernTier: 4, attack: 4, health: 3, keywords: [], tribes: ['beast'], effects: [{ trigger: 'sell', target: 'random', tribe: 'beast', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-cannoneer', name: L('Канонир', 'Cannoneer'), description: L('В начале боя: +3 к атаке.', 'Start of combat: +3 attack.'), tavernTier: 4, attack: 5, health: 3, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'startCombat', target: 'self', action: { kind: 'buff', attack: 3, health: 0 } }] },

  // ── Tier 5 ──
  { id: 'ab-hydra', name: L('Гидра', 'Hydra'), description: L('Предсмертный хрип: призывает два Жетона 1/1.', 'Deathrattle: summon two 1/1 Tokens.'), tavernTier: 5, attack: 2, health: 8, keywords: ['deathrattle'], tribes: ['beast'], deathrattle: { summonId: 'ab-token-1-1', count: 2 } },
  { id: 'ab-assassin', name: L('Убийца', 'Assassin'), tavernTier: 5, attack: 6, health: 3, keywords: ['poisonous'], tribes: ['pirate'] },
  { id: 'ab-ashes', name: L('Пепел', 'Ashes'), tavernTier: 5, attack: 4, health: 2, keywords: ['reborn'], tribes: ['undead'] },
  { id: 'ab-magnetron', name: L('Магнетрон', 'Magnetron'), description: L('Купили механизм — +2/+2.', 'After you buy a mech: +2/+2.'), tavernTier: 5, attack: 5, health: 5, keywords: ['divineShield'], tribes: ['mech'], effects: [{ trigger: 'buy', onTribe: 'mech', target: 'self', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-admiral', name: L('Адмирал', 'Admiral'), description: L('В конце хода: ваши пираты получают +2/+1.', 'At the end of your turn: your pirates get +2/+1.'), tavernTier: 5, attack: 5, health: 5, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'endTurn', target: 'friendly', tribe: 'pirate', action: { kind: 'buff', attack: 2, health: 1 } }] },
  { id: 'ab-bone-king', name: L('Костяной король', 'Bone King'), description: L('Предсмертный хрип: ваша нежить получает +3/+3.', 'Deathrattle: your undead get +3/+3.'), tavernTier: 5, attack: 5, health: 6, keywords: ['deathrattle'], tribes: ['undead'], effects: [{ trigger: 'deathrattle', target: 'friendly', tribe: 'undead', action: { kind: 'buff', attack: 3, health: 3 } }] },
  { id: 'ab-primal', name: L('Первозверь', 'Primal Beast'), description: L('Боевой клич: ваши звери получают +3/+3.', 'Battlecry: your beasts get +3/+3.'), tavernTier: 5, attack: 6, health: 6, keywords: ['battlecry'], tribes: ['beast'], effects: [{ trigger: 'battlecry', target: 'friendly', tribe: 'beast', action: { kind: 'buff', attack: 3, health: 3 } }] },
  { id: 'ab-golem', name: L('Голем', 'Golem'), tavernTier: 5, attack: 7, health: 7, keywords: ['taunt'], tribes: ['neutral'] },

  // ── Tier 6 ──
  { id: 'ab-colossus', name: L('Колосс', 'Colossus'), tavernTier: 6, attack: 8, health: 8, keywords: [], tribes: ['mech'] },
  { id: 'ab-omen', name: L('Знамение', 'Omen'), tavernTier: 6, attack: 6, health: 7, keywords: ['taunt', 'divineShield'], tribes: ['undead'] },
  { id: 'ab-leviathan', name: L('Левиафан', 'Leviathan'), description: L('Предсмертный хрип: призывает двух Медведей 3/3.', 'Deathrattle: summon two 3/3 Bears.'), tavernTier: 6, attack: 7, health: 9, keywords: ['deathrattle'], tribes: ['beast'], deathrattle: { summonId: 'ab-token-cub', count: 2 } },
  { id: 'ab-dreadnought', name: L('Дредноут', 'Dreadnought'), description: L('Боевой клич: ваши пираты получают +3/+3.', 'Battlecry: your pirates get +3/+3.'), tavernTier: 6, attack: 6, health: 9, keywords: ['taunt', 'battlecry'], tribes: ['pirate'], effects: [{ trigger: 'battlecry', target: 'friendly', tribe: 'pirate', action: { kind: 'buff', attack: 3, health: 3 } }] },
  { id: 'ab-necropolis', name: L('Некрополь', 'Necropolis'), description: L('Предсмертный хрип: призывает трёх Скелетов-слуг 2/1.', 'Deathrattle: summon three 2/1 Bone Servants.'), tavernTier: 6, attack: 5, health: 9, keywords: ['reborn', 'deathrattle'], tribes: ['undead'], deathrattle: { summonId: 'ab-token-skel', count: 3 } },
  { id: 'ab-overclocker', name: L('Разгонщик', 'Overclocker'), description: L('В конце хода: ваши механизмы получают +2/+2.', 'At the end of your turn: your mechs get +2/+2.'), tavernTier: 6, attack: 6, health: 6, keywords: [], tribes: ['mech'], effects: [{ trigger: 'endTurn', target: 'friendly', tribe: 'mech', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-titan', name: L('Титан', 'Titan'), description: L('Триплет: +4/+4.', 'Whenever you make a triple: +4/+4.'), tavernTier: 6, attack: 9, health: 9, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'triple', target: 'self', action: { kind: 'buff', attack: 4, health: 4 } }] },
  // ── Tokens for the expansion ──
  { id: 'ab-token-microbot', name: L('Ученик сварщика', 'Welder Apprentice'), tavernTier: 1, attack: 1, health: 1, keywords: [], tribes: ['mech'], token: true, inTavern: false, inDiscover: false },
  { id: 'ab-token-hound', name: L('Чушка-гончая', 'Hound Sow'), tavernTier: 1, attack: 2, health: 1, keywords: [], tribes: ['beast'], token: true, inTavern: false, inDiscover: false },
  { id: 'ab-token-raptor', name: L('Кабан-хищник', 'Boar Raptor'), tavernTier: 2, attack: 3, health: 2, keywords: [], tribes: ['beast'], token: true, inTavern: false, inDiscover: false },
  { id: 'ab-token-drake', name: L('Дракончик', 'Drake'), tavernTier: 1, attack: 2, health: 2, keywords: [], tribes: ['dragon'], token: true, inTavern: false, inDiscover: false },
  { id: 'ab-token-shade', name: L('Тень', 'Shade'), tavernTier: 1, attack: 1, health: 1, keywords: ['reborn'], tribes: ['undead'], token: true, inTavern: false, inDiscover: false },
  { id: 'ab-token-sailor', name: L('Матрос', 'Sailor'), tavernTier: 1, attack: 1, health: 1, keywords: [], tribes: ['pirate'], token: true, inTavern: false, inDiscover: false },

  // ── Expansion · Tier 1 ──
  { id: 'ab-annoyer', name: L('Бесилка', 'Annoyer'), tavernTier: 1, attack: 1, health: 2, keywords: ['taunt', 'divineShield'], tribes: ['mech'] },
  { id: 'ab-sky-pirate', name: L('Шкет', 'Sky Pirate'), description: L('Предсмертный хрип: призывает Матроса 1/1.', 'Deathrattle: summon a 1/1 Sailor.'), tavernTier: 1, attack: 2, health: 1, keywords: ['deathrattle'], tribes: ['pirate'], deathrattle: { summonId: 'ab-token-sailor', count: 1 } },
  { id: 'ab-harvester', name: L('Жнец душ', 'Soul Harvester'), description: L('Предсмертный хрип: ваша нежить получает +1/+1.', 'Deathrattle: your undead get +1/+1.'), tavernTier: 1, attack: 1, health: 2, keywords: ['deathrattle'], tribes: ['undead'], effects: [{ trigger: 'deathrattle', target: 'friendly', tribe: 'undead', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-whelpling', name: L('Змеёныш-дракон', 'Whelpling'), description: L('Ваш дракон атаковал — +1 к атаке.', 'After a friendly dragon attacks: +1 attack.'), tavernTier: 1, attack: 2, health: 1, keywords: [], tribes: ['dragon'], effects: [{ trigger: 'friendlyAttack', onTribe: 'dragon', target: 'self', action: { kind: 'buff', attack: 1, health: 0 } }] },
  { id: 'ab-red-whelp', name: L('Огненный змей', 'Red Whelp'), description: L('В начале боя: +1 к атаке за каждого вашего дракона.', 'Start of combat: +1 attack for each friendly dragon.'), tavernTier: 1, attack: 1, health: 2, keywords: [], tribes: ['dragon'], effects: [{ trigger: 'startCombat', target: 'self', per: 'minions', perTribe: 'dragon', action: { kind: 'buff', attack: 1, health: 0 } }] },
  { id: 'ab-sellsword', name: L('Наёмник Порошенко', 'Poroshenko the Sellsword'), description: L('Обновили таверну — +1 к атаке.', 'After you refresh the tavern: +1 attack.'), tavernTier: 1, attack: 1, health: 2, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'reroll', target: 'self', action: { kind: 'buff', attack: 1, health: 0 } }] },
    { id: 'ab-scribe', name: L('Писарь Зеленский', 'Zelensky the Scribe'), description: L('В конце хода: существа в руке получают +1/+1.', 'At the end of your turn: minions in your hand get +1/+1.'), tavernTier: 1, attack: 1, health: 3, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'endTurn', target: 'hand', tribe: 'all', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-zookeeper', name: L('Зеленский-смотритель', 'Zelensky the Zookeeper'), description: L('Боевой клич: +1/+1 за каждый тип существ на столе.', 'Battlecry: +1/+1 for each minion type on your board.'), tavernTier: 1, attack: 2, health: 2, keywords: ['battlecry'], tribes: ['neutral'], effects: [{ trigger: 'battlecry', target: 'self', per: 'tribes', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-bilge-rat', name: L('Трюмная крыса', 'Bilge Rat'), description: L('Зверь и пират. Продаётся за 2 доллара.', 'Beast and pirate. Sells for 2 gold.'), tavernTier: 1, attack: 1, health: 2, keywords: [], tribes: ['beast', 'pirate'], effects: [{ trigger: 'sell', action: { kind: 'gold', amount: 1 } }] },
  { id: 'ab-corpse-flower', name: L('Трупоцвет', 'Corpse Flower'), description: L('Ваша нежить погибла — +2 к атаке.', 'Whenever a friendly undead dies: +2 attack.'), tavernTier: 1, attack: 0, health: 3, keywords: ['taunt'], tribes: ['undead'], effects: [{ trigger: 'friendlyDeath', onTribe: 'undead', target: 'self', action: { kind: 'buff', attack: 2, health: 0 } }] },
  { id: 'ab-shield-mite', name: L('Клещ-сварщик', 'Shield Mite Welder'), description: L('Ваше существо потеряло щит — +1/+1.', 'Whenever a friendly minion loses Divine Shield: +1/+1.'), tavernTier: 1, attack: 1, health: 1, keywords: ['divineShield'], tribes: ['mech'], effects: [{ trigger: 'shieldPop', target: 'self', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-cabin-boy', name: L('Каютный юнга', 'Cabin Boy'), description: L('Ваш пират атаковал — +1/+1.', 'After a friendly pirate attacks: +1/+1.'), tavernTier: 1, attack: 1, health: 3, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'friendlyAttack', onTribe: 'pirate', target: 'self', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-egg', name: L('Яйцо кабана-хищника', 'Boar Raptor Egg'), description: L('Не атакует. Предсмертный хрип: призывает Кабана-хищника 3/2.', 'Cannot attack. Deathrattle: summon a 3/2 Boar Raptor.'), tavernTier: 1, attack: 0, health: 3, keywords: ['cannotAttack', 'deathrattle'], tribes: ['beast'], deathrattle: { summonId: 'ab-token-raptor', count: 1 } },
  { id: 'ab-bone-dog', name: L('Костяная псина', 'Bone Dog'), description: L('Зверь и нежить.', 'Beast and undead.'), tavernTier: 1, attack: 2, health: 1, keywords: ['reborn'], tribes: ['beast', 'undead'] },
  { id: 'ab-tin-soldier', name: L('Оловянный сварщик', 'Tin Welder'), description: L('Боевой клич: случайный ваш заводчанин получает щит.', 'Battlecry: a random friendly factory worker gains Divine Shield.'), tavernTier: 1, attack: 2, health: 2, keywords: ['battlecry'], tribes: ['mech'], effects: [{ trigger: 'battlecry', target: 'random', tribe: 'mech', action: { kind: 'keyword', keyword: 'divineShield' } }] },
  { id: 'ab-magpie', name: L('Сорока-свинья', 'Magpie Pig'), description: L('Купили существо — свиньи в руке получают +1/+1.', 'After you buy a minion: pigs in your hand get +1/+1.'), tavernTier: 1, attack: 1, health: 2, keywords: [], tribes: ['beast'], effects: [{ trigger: 'buy', target: 'hand', tribe: 'beast', action: { kind: 'buff', attack: 1, health: 1 } }] },

  // ── Expansion · Tier 2 ──
  { id: 'ab-hyena', name: L('Свинья-гиена', 'Pig Hyena'), description: L('Ваша свинья погибла — +2/+1.', 'Whenever a friendly pig dies: +2/+1.'), tavernTier: 2, attack: 2, health: 2, keywords: [], tribes: ['beast'], effects: [{ trigger: 'friendlyDeath', onTribe: 'beast', target: 'self', action: { kind: 'buff', attack: 2, health: 1 } }] },
  { id: 'ab-kennel', name: L('Свинарник гончих', 'Hound Pigsty'), description: L('Предсмертный хрип: призывает двух Чушек-гончих 2/1.', 'Deathrattle: summon two 2/1 Hound Sows.'), tavernTier: 2, attack: 1, health: 4, keywords: ['deathrattle'], tribes: ['beast'], deathrattle: { summonId: 'ab-token-hound', count: 2 } },
  { id: 'ab-selfless', name: L('Самоотверженный Кличко', 'Selfless Klitschko'), description: L('Предсмертный хрип: случайное ваше существо получает щит.', 'Deathrattle: a random friendly minion gains Divine Shield.'), tavernTier: 2, attack: 2, health: 1, keywords: ['deathrattle'], tribes: ['neutral'], effects: [{ trigger: 'deathrattle', target: 'random', tribe: 'all', action: { kind: 'keyword', keyword: 'divineShield' } }] },
  { id: 'ab-carousel', name: L('Карусель Порошенко', 'Poroshenko Carousel'), description: L('В конце хода: случайное ваше существо получает +1/+1 за каждый тип на столе.', 'At the end of your turn: a random friendly minion gets +1/+1 for each minion type on your board.'), tavernTier: 2, attack: 2, health: 3, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'endTurn', target: 'random', tribe: 'all', per: 'tribes', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-bronze-warden', name: L('Бронзовый страж', 'Bronze Warden'), tavernTier: 2, attack: 2, health: 1, keywords: ['divineShield', 'reborn'], tribes: ['dragon'] },
  { id: 'ab-glyph-guardian', name: L('Хранитель глифов', 'Glyph Guardian'), description: L('Ваш дракон атаковал — он получает +1 к атаке.', 'After a friendly dragon attacks: it gains +1 attack.'), tavernTier: 2, attack: 2, health: 4, keywords: [], tribes: ['dragon'], effects: [{ trigger: 'friendlyAttack', onTribe: 'dragon', target: 'subject', action: { kind: 'buff', attack: 1, health: 0 } }] },
  { id: 'ab-deflector', name: L('Сварщик-отражатель', 'Deflector Welder'), description: L('Ваш заводчанин потерял щит — +1/+1.', 'Whenever a friendly factory worker loses Divine Shield: +1/+1.'), tavernTier: 2, attack: 3, health: 2, keywords: ['divineShield'], tribes: ['mech'], effects: [{ trigger: 'shieldPop', onTribe: 'mech', target: 'self', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-freebooter', name: L('Флибустьер', 'Freebooter'), description: L('Обновили таверну — ваши пираты получают +1 к атаке.', 'After you refresh the tavern: your pirates get +1 attack.'), tavernTier: 2, attack: 2, health: 3, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'reroll', target: 'friendly', tribe: 'pirate', action: { kind: 'buff', attack: 1, health: 0 } }] },
  { id: 'ab-first-mate', name: L('Старпом', 'First Mate'), description: L('Купленный пират получает +1/+1.', 'After you buy a pirate, it gets +1/+1.'), tavernTier: 2, attack: 3, health: 2, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'buy', onTribe: 'pirate', target: 'bought', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-necro-apprentice', name: L('Ученик некроманта', 'Necro Apprentice'), description: L('Продали нежить — ваша нежить получает +1/+1.', 'Whenever you sell an undead: your undead get +1/+1.'), tavernTier: 2, attack: 2, health: 2, keywords: [], tribes: ['undead'], effects: [{ trigger: 'sell', onTribe: 'undead', target: 'friendly', tribe: 'undead', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-wraith', name: L('Призрак', 'Wraith'), description: L('Ваше существо с возрождением погибло — +1/+1.', 'Whenever a friendly Reborn minion dies: +1/+1.'), tavernTier: 2, attack: 3, health: 1, keywords: ['reborn'], tribes: ['undead'], effects: [{ trigger: 'friendlyDeath', onKeyword: 'reborn', target: 'self', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-lookout', name: L('Дозорный Аваков', 'Avakov the Lookout'), description: L('В конце хода: существа в руке получают +1 к атаке.', 'At the end of your turn: minions in your hand get +1 attack.'), tavernTier: 2, attack: 2, health: 3, keywords: ['taunt'], tribes: ['neutral'], effects: [{ trigger: 'endTurn', target: 'hand', tribe: 'all', action: { kind: 'buff', attack: 1, health: 0 } }] },
  { id: 'ab-brood', name: L('Свиной выводок', 'Pig Brood'), description: L('Сыгранная свинья получает +1/+1.', 'Whenever you play a pig, it gets +1/+1.'), tavernTier: 2, attack: 1, health: 2, keywords: [], tribes: ['beast'], effects: [{ trigger: 'play', onTribe: 'beast', target: 'subject', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-bottler', name: L('Тимошенко-разливщица', 'Tymoshenko the Bottler'), description: L('Боевой клич: случайная ваша свинья получает яд.', 'Battlecry: a random friendly pig gains Poisonous.'), tavernTier: 2, attack: 2, health: 2, keywords: ['battlecry'], tribes: ['neutral'], effects: [{ trigger: 'battlecry', target: 'random', tribe: 'beast', action: { kind: 'keyword', keyword: 'poisonous' } }] },
  { id: 'ab-gear-hoarder', name: L('Скопидом-слесарь', 'Gear Hoarder Locksmith'), description: L('Обновили таверну — заводчане в руке получают +1/+1.', 'After you refresh the tavern: factory workers in your hand get +1/+1.'), tavernTier: 2, attack: 2, health: 2, keywords: [], tribes: ['mech'], effects: [{ trigger: 'reroll', target: 'hand', tribe: 'mech', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-dragon-egg', name: L('Драконье яйцо', 'Dragon Egg'), description: L('Не атакует. Предсмертный хрип: призывает Дракончика 2/2.', 'Cannot attack. Deathrattle: summon a 2/2 Drake.'), tavernTier: 2, attack: 0, health: 2, keywords: ['cannotAttack', 'deathrattle'], tribes: ['dragon'], deathrattle: { summonId: 'ab-token-drake', count: 1 } },

  // ── Expansion · Tier 3 ──
  { id: 'ab-rat-king', name: L('Свиной король', 'Pig King'), description: L('Ваша свинья погибла — ваши свиньи получают +1 к атаке.', 'Whenever a friendly pig dies: your pigs get +1 attack.'), tavernTier: 3, attack: 2, health: 4, keywords: [], tribes: ['beast'], effects: [{ trigger: 'friendlyDeath', onTribe: 'beast', target: 'friendly', tribe: 'beast', action: { kind: 'buff', attack: 1, health: 0 } }] },
  { id: 'ab-poison-frog', name: L('Ядовитая свинья-жаба', 'Poison Pig Frog'), tavernTier: 3, attack: 1, health: 1, keywords: ['poisonous', 'divineShield'], tribes: ['beast'] },
  { id: 'ab-module', name: L('Модуль сварщика', 'Welder Module'), description: L('Купленный заводчанин получает щит.', 'After you buy a factory worker, it gains Divine Shield.'), tavernTier: 3, attack: 1, health: 3, keywords: ['taunt', 'divineShield'], tribes: ['mech'], effects: [{ trigger: 'buy', onTribe: 'mech', target: 'bought', action: { kind: 'keyword', keyword: 'divineShield' } }] },
  { id: 'ab-cobalt', name: L('Кобальтовый слесарь', 'Cobalt Locksmith'), description: L('Ваше существо потеряло щит — ваши заводчане получают +1/+1.', 'Whenever a friendly minion loses Divine Shield: your factory workers get +1/+1.'), tavernTier: 3, attack: 3, health: 3, keywords: [], tribes: ['mech'], effects: [{ trigger: 'shieldPop', target: 'friendly', tribe: 'mech', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-southsea', name: L('Капитан Южных морей', 'Southsea Captain'), description: L('Другие ваши пираты получают +1 к атаке в бою.', 'Your other pirates have +1 attack in combat.'), tavernTier: 3, attack: 3, health: 3, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'aura', tribe: 'pirate', action: { kind: 'aura', attack: 1 } }] },
  { id: 'ab-looter', name: L('Мародёр', 'Salty Looter'), description: L('Сыграли пирата — +1/+1.', 'Whenever you play a pirate: +1/+1.'), tavernTier: 3, attack: 3, health: 3, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'play', onTribe: 'pirate', target: 'self', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-coin-flipper', name: L('Крутила', 'Coin Flipper'), description: L('Обновили таверну — +2/+1.', 'After you refresh the tavern: +2/+1.'), tavernTier: 3, attack: 2, health: 2, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'reroll', target: 'self', action: { kind: 'buff', attack: 2, health: 1 } }] },
  { id: 'ab-crypt-lord', name: L('Владыка склепа', 'Crypt Lord'), description: L('Ваше существо погибло — +1/+1.', 'Whenever a friendly minion dies: +1/+1.'), tavernTier: 3, attack: 2, health: 5, keywords: ['taunt'], tribes: ['undead'], effects: [{ trigger: 'friendlyDeath', target: 'self', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-ghoul-pack', name: L('Стая гулей', 'Ghoul Pack'), description: L('Предсмертный хрип: призывает две Тени 1/1 с возрождением.', 'Deathrattle: summon two 1/1 Shades with Reborn.'), tavernTier: 3, attack: 3, health: 3, keywords: ['deathrattle'], tribes: ['undead'], deathrattle: { summonId: 'ab-token-shade', count: 2 } },
  { id: 'ab-bronze-drake', name: L('Бронзовый дракон', 'Bronze Drake'), description: L('В начале боя: ваши драконы получают +1/+1.', 'Start of combat: your dragons get +1/+1.'), tavernTier: 3, attack: 3, health: 4, keywords: [], tribes: ['dragon'], effects: [{ trigger: 'startCombat', target: 'friendly', tribe: 'dragon', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-hangry-dragon', name: L('Голодный дракон', 'Hangry Dragon'), description: L('Ваш дракон атаковал — +1/+1.', 'After a friendly dragon attacks: +1/+1.'), tavernTier: 3, attack: 4, health: 4, keywords: [], tribes: ['dragon'], effects: [{ trigger: 'friendlyAttack', onTribe: 'dragon', target: 'self', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-bard', name: L('Бард Зеленский', 'Bard Zelensky'), description: L('Боевой клич: соседи получают +1/+1 за каждый тип на столе.', 'Battlecry: adjacent minions get +1/+1 for each minion type on your board.'), tavernTier: 3, attack: 3, health: 3, keywords: ['battlecry'], tribes: ['neutral'], effects: [{ trigger: 'battlecry', target: 'adjacent', per: 'tribes', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-trainer', name: L('Тренер Тимошенко', 'Trainer Tymoshenko'), description: L('Купили существо — существа в руке получают +1 к атаке.', 'After you buy a minion: minions in your hand get +1 attack.'), tavernTier: 3, attack: 2, health: 4, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'buy', target: 'hand', tribe: 'all', action: { kind: 'buff', attack: 1, health: 0 } }] },
  { id: 'ab-shieldbearer', name: L('Щитоносец Яценюк', 'Shieldbearer Yatsenyuk'), description: L('Ваше существо потеряло щит — +2 к атаке.', 'Whenever a friendly minion loses Divine Shield: +2 attack.'), tavernTier: 3, attack: 1, health: 6, keywords: ['taunt', 'divineShield'], tribes: ['neutral'], effects: [{ trigger: 'shieldPop', target: 'self', action: { kind: 'buff', attack: 2, health: 0 } }] },
  { id: 'ab-twin-blade', name: L('Двуручник Ляшко', 'Two-Hander Lyashko'), tavernTier: 3, attack: 2, health: 3, keywords: ['windfury'], tribes: ['neutral'] },

  // ── Expansion · Tier 4 ──
  { id: 'ab-drakonid', name: L('Драконид-каратель', 'Drakonid Enforcer'), description: L('Ваше существо потеряло щит — +2/+2.', 'Whenever a friendly minion loses Divine Shield: +2/+2.'), tavernTier: 4, attack: 3, health: 6, keywords: [], tribes: ['dragon'], effects: [{ trigger: 'shieldPop', target: 'self', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-boar', name: L('Кабан-секач', 'Cleaver Boar'), tavernTier: 4, attack: 2, health: 5, keywords: ['cleave'], tribes: ['beast'] },
  { id: 'ab-hunter', name: L('Свиной ловчий', 'Pig Hunter'), description: L('Сыгранная свинья получает +2/+2.', 'Whenever you play a pig, it gets +2/+2.'), tavernTier: 4, attack: 4, health: 3, keywords: [], tribes: ['beast'], effects: [{ trigger: 'play', onTribe: 'beast', target: 'subject', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-rover', name: L('Патрульный сварщик', 'Security Welder'), description: L('Предсмертный хрип: призывает трёх Учеников сварщика 1/1.', 'Deathrattle: summon three 1/1 Welder Apprentices.'), tavernTier: 4, attack: 2, health: 6, keywords: ['taunt', 'deathrattle'], tribes: ['mech'], deathrattle: { summonId: 'ab-token-microbot', count: 3 } },
  { id: 'ab-holy-mech', name: L('Святой сварщик', 'Holy Welder'), description: L('В начале боя: случайный ваш заводчанин получает щит.', 'Start of combat: a random friendly factory worker gains Divine Shield.'), tavernTier: 4, attack: 4, health: 4, keywords: ['divineShield'], tribes: ['mech'], effects: [{ trigger: 'startCombat', target: 'random', tribe: 'mech', action: { kind: 'keyword', keyword: 'divineShield' } }] },
  { id: 'ab-barker', name: L('Зазывала Зеленский', 'Barker Zelensky'), description: L('В конце хода: +1/+1 за каждый тип на столе.', 'At the end of your turn: +1/+1 for each minion type on your board.'), tavernTier: 4, attack: 2, health: 2, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'endTurn', target: 'self', per: 'tribes', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-ripsnarl', name: L('Капитан Рипснарл', 'Captain Ripsnarl'), description: L('Ваш пират атаковал — ваши пираты получают +1 к атаке.', 'After a friendly pirate attacks: your pirates get +1 attack.'), tavernTier: 4, attack: 4, health: 5, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'friendlyAttack', onTribe: 'pirate', target: 'friendly', tribe: 'pirate', action: { kind: 'buff', attack: 1, health: 0 } }] },
  { id: 'ab-bosun', name: L('Боцман', 'Bosun'), description: L('Обновили таверну — ваши пираты получают +1/+1.', 'After you refresh the tavern: your pirates get +1/+1.'), tavernTier: 4, attack: 3, health: 5, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'reroll', target: 'friendly', tribe: 'pirate', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-dark-priestess', name: L('Тёмная жрица', 'Dark Priestess'), description: L('Ваша нежить погибла — ваша нежить получает +1/+1.', 'Whenever a friendly undead dies: your undead get +1/+1.'), tavernTier: 4, attack: 4, health: 4, keywords: [], tribes: ['undead'], effects: [{ trigger: 'friendlyDeath', onTribe: 'undead', target: 'friendly', tribe: 'undead', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-bone-baron', name: L('Костяной барон', 'Bone Baron'), description: L('Боевой клич: случайная ваша нежить получает возрождение.', 'Battlecry: a random friendly undead gains Reborn.'), tavernTier: 4, attack: 3, health: 5, keywords: ['battlecry'], tribes: ['undead'], effects: [{ trigger: 'battlecry', target: 'random', tribe: 'undead', action: { kind: 'keyword', keyword: 'reborn' } }] },
  { id: 'ab-magician', name: L('Фокусник Порошенко', 'Magician Poroshenko'), description: L('Боевой клич: случайное ваше существо получает +2/+2 за каждый тип на столе.', 'Battlecry: a random friendly minion gets +2/+2 for each minion type on your board.'), tavernTier: 4, attack: 4, health: 4, keywords: ['battlecry'], tribes: ['neutral'], effects: [{ trigger: 'battlecry', target: 'random', tribe: 'all', per: 'tribes', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-mentor', name: L('Наставник Кличко', 'Mentor Klitschko'), description: L('В конце хода: существа в руке получают +2/+2.', 'At the end of your turn: minions in your hand get +2/+2.'), tavernTier: 4, attack: 3, health: 5, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'endTurn', target: 'hand', tribe: 'all', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-poisoner', name: L('Отравитель Медведчук', 'Poisoner Medvedchuk'), description: L('Боевой клич: случайное ваше существо получает яд.', 'Battlecry: a random friendly minion gains Poisonous.'), tavernTier: 4, attack: 3, health: 3, keywords: ['battlecry'], tribes: ['neutral'], effects: [{ trigger: 'battlecry', target: 'random', tribe: 'all', action: { kind: 'keyword', keyword: 'poisonous' } }] },
  { id: 'ab-windcaller', name: L('Ветродуй Тимошенко', 'Windcaller Tymoshenko'), description: L('Боевой клич: случайное ваше существо получает двойной удар.', 'Battlecry: a random friendly minion gains Windfury.'), tavernTier: 4, attack: 4, health: 3, keywords: ['battlecry'], tribes: ['neutral'], effects: [{ trigger: 'battlecry', target: 'random', tribe: 'all', action: { kind: 'keyword', keyword: 'windfury' } }] },
  { id: 'ab-twilight-drake', name: L('Сумеречный дракон', 'Twilight Drake'), description: L('В начале боя: +1/+1 за каждого вашего дракона.', 'Start of combat: +1/+1 for each friendly dragon.'), tavernTier: 4, attack: 4, health: 4, keywords: [], tribes: ['dragon'], effects: [{ trigger: 'startCombat', target: 'self', per: 'minions', perTribe: 'dragon', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-whelp-mother', name: L('Мать драконят', 'Whelp Mother'), description: L('Предсмертный хрип: призывает двух Дракончиков 2/2.', 'Deathrattle: summon two 2/2 Drakes.'), tavernTier: 4, attack: 3, health: 5, keywords: ['deathrattle'], tribes: ['dragon'], deathrattle: { summonId: 'ab-token-drake', count: 2 } },

  // ── Expansion · Tier 5 ──
  { id: 'ab-mama-bear', name: L('Свиноматка-великанша', 'Giant Sow'), description: L('Сыгранная свинья получает +4/+4.', 'Whenever you play a pig, it gets +4/+4.'), tavernTier: 5, attack: 5, health: 5, keywords: [], tribes: ['beast'], effects: [{ trigger: 'play', onTribe: 'beast', target: 'subject', action: { kind: 'buff', attack: 4, health: 4 } }] },
  { id: 'ab-grave-titan', name: L('Могильный титан', 'Grave Titan'), description: L('Ваше существо погибло — призывает Скелета-слугу 2/1.', 'Whenever a friendly minion dies: summon a 2/1 Bone Servant.'), tavernTier: 5, attack: 6, health: 6, keywords: [], tribes: ['undead'], effects: [{ trigger: 'friendlyDeath', action: { kind: 'summon', summonId: 'ab-token-skel', count: 1 } }] },
  { id: 'ab-junkbot', name: L('Петрович-исполин', 'Petrovich the Giant'), description: L('Ваш заводчанин погиб — +2/+2.', 'Whenever a friendly factory worker dies: +2/+2.'), tavernTier: 5, attack: 1, health: 5, keywords: [], tribes: ['mech'], effects: [{ trigger: 'friendlyDeath', onTribe: 'mech', target: 'self', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-shield-chain', name: L('Сварная цепь', 'Welded Chain'), description: L('Ваше существо потеряло щит — случайный ваш заводчанин получает щит.', 'Whenever a friendly minion loses Divine Shield: a random friendly factory worker gains Divine Shield.'), tavernTier: 5, attack: 4, health: 6, keywords: ['divineShield'], tribes: ['mech'], effects: [{ trigger: 'shieldPop', target: 'random', tribe: 'mech', action: { kind: 'keyword', keyword: 'divineShield' } }] },
  { id: 'ab-hoggarr', name: L('Капитан Хоггар', 'Captain Hoggarr'), description: L('Купили пирата — +1 доллар.', 'After you buy a pirate: gain 1 gold.'), tavernTier: 5, attack: 6, health: 6, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'buy', onTribe: 'pirate', action: { kind: 'gold', amount: 1 } }] },
  { id: 'ab-corsair-queen', name: L('Королева корсаров', 'Corsair Queen'), description: L('Ваш пират атаковал — он получает +2/+2.', 'After a friendly pirate attacks: it gains +2/+2.'), tavernTier: 5, attack: 5, health: 5, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'friendlyAttack', onTribe: 'pirate', target: 'subject', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-razorgore', name: L('Разорогор', 'Razorgore'), description: L('В конце хода: +1/+1 за каждого вашего дракона.', 'At the end of your turn: +1/+1 for each friendly dragon.'), tavernTier: 5, attack: 4, health: 6, keywords: [], tribes: ['dragon'], effects: [{ trigger: 'endTurn', target: 'self', per: 'minions', perTribe: 'dragon', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-aspect', name: L('Аспект магии', 'Aspect of Magic'), description: L('Сыграли существо с боевым кличем — ваши драконы получают +1/+1.', 'Whenever you play a Battlecry minion: your dragons get +1/+1.'), tavernTier: 5, attack: 4, health: 10, keywords: [], tribes: ['dragon'], effects: [{ trigger: 'play', onKeyword: 'battlecry', target: 'friendly', tribe: 'dragon', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-lightfang', name: L('Светоклык Яценюк', 'Lightfang Yatsenyuk'), description: L('В конце хода: случайное ваше существо получает +2/+2 за каждый тип на столе.', 'At the end of your turn: a random friendly minion gets +2/+2 for each minion type on your board.'), tavernTier: 5, attack: 2, health: 2, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'endTurn', target: 'random', tribe: 'all', per: 'tribes', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-ringmaster', name: L('Распорядитель Аваков', 'Ringmaster Avakov'), description: L('Боевой клич: соседи получают +2/+2 за каждый тип на столе.', 'Battlecry: adjacent minions get +2/+2 for each minion type on your board.'), tavernTier: 5, attack: 5, health: 5, keywords: ['battlecry'], tribes: ['neutral'], effects: [{ trigger: 'battlecry', target: 'adjacent', per: 'tribes', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-hand-master', name: L('Ляшко-хранитель', 'Lyashko the Hand Master'), description: L('Купили существо — существа в руке получают +1/+1.', 'After you buy a minion: minions in your hand get +1/+1.'), tavernTier: 5, attack: 5, health: 5, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'buy', target: 'hand', tribe: 'all', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-poison-master', name: L('Свинья-отравительница', 'Pig Poison Mistress'), description: L('В конце хода: случайная ваша свинья получает яд.', 'At the end of your turn: a random friendly pig gains Poisonous.'), tavernTier: 5, attack: 4, health: 4, keywords: ['poisonous'], tribes: ['beast'], effects: [{ trigger: 'endTurn', target: 'random', tribe: 'beast', action: { kind: 'keyword', keyword: 'poisonous' } }] },

  // ── Expansion · Tier 6 ──
  { id: 'ab-many-heads', name: L('Многоглавый хряк', 'Many-Headed Boar'), description: L('Предсмертный хрип: призывает двух Кабанов-хищников 3/2.', 'Deathrattle: summon two 3/2 Boar Raptors.'), tavernTier: 6, attack: 7, health: 7, keywords: ['deathrattle'], tribes: ['beast'], deathrattle: { summonId: 'ab-token-raptor', count: 2 } },
  { id: 'ab-reaper-4000', name: L('Жнец-4000 Петрович', 'Reaper 4000 Petrovich'), tavernTier: 6, attack: 6, health: 9, keywords: ['cleave'], tribes: ['mech'] },
  { id: 'ab-nadina', name: L('Надина Розенберг', 'Nadina Rosenberg'), description: L('Предсмертный хрип: ваши драконы получают щит.', 'Deathrattle: your dragons gain Divine Shield.'), tavernTier: 6, attack: 7, health: 4, keywords: ['deathrattle'], tribes: ['neutral'], effects: [{ trigger: 'deathrattle', target: 'friendly', tribe: 'dragon', action: { kind: 'keyword', keyword: 'divineShield' } }] },
  { id: 'ab-amalgam', name: L('Амальгам Зеленский', 'Amalgam Zelensky'), description: L('Свинья, заводчанин и пират. Боевой клич: +2/+2 за каждый тип на столе.', 'Pig, factory worker and pirate. Battlecry: +2/+2 for each minion type on your board.'), tavernTier: 6, attack: 6, health: 6, keywords: ['battlecry'], tribes: ['beast', 'mech', 'pirate'], effects: [{ trigger: 'battlecry', target: 'self', per: 'tribes', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-goldrinn', name: L('Свиной Голдринн', 'Pig Goldrinn'), description: L('Предсмертный хрип: ваши свиньи получают +4/+4.', 'Deathrattle: your pigs get +4/+4.'), tavernTier: 6, attack: 4, health: 4, keywords: ['deathrattle'], tribes: ['beast'], effects: [{ trigger: 'deathrattle', target: 'friendly', tribe: 'beast', action: { kind: 'buff', attack: 4, health: 4 } }] },
  { id: 'ab-spider-queen', name: L('Паучиха-свинья', 'Spider Pig Queen'), tavernTier: 6, attack: 2, health: 8, keywords: ['poisonous', 'taunt'], tribes: ['beast'] },
  { id: 'ab-eliza', name: L('Королева пиратов', 'Pirate Queen'), description: L('Ваш пират атаковал — ваши существа получают +1/+1.', 'After a friendly pirate attacks: your minions get +1/+1.'), tavernTier: 6, attack: 6, health: 7, keywords: [], tribes: ['pirate'], effects: [{ trigger: 'friendlyAttack', onTribe: 'pirate', target: 'friendly', tribe: 'all', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-lord-of-bones', name: L('Повелитель костей', 'Lord of Bones'), description: L('Ваша нежить погибла — ваша нежить получает +2/+2.', 'Whenever a friendly undead dies: your undead get +2/+2.'), tavernTier: 6, attack: 5, health: 9, keywords: ['reborn'], tribes: ['undead'], effects: [{ trigger: 'friendlyDeath', onTribe: 'undead', target: 'friendly', tribe: 'undead', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-tarecgosa', name: L('Тарекгоса', 'Tarecgosa'), description: L('Ваш дракон атаковал — ваши драконы получают +1/+1.', 'After a friendly dragon attacks: your dragons get +1/+1.'), tavernTier: 6, attack: 6, health: 8, keywords: [], tribes: ['dragon'], effects: [{ trigger: 'friendlyAttack', onTribe: 'dragon', target: 'friendly', tribe: 'dragon', action: { kind: 'buff', attack: 1, health: 1 } }] },
  { id: 'ab-omega-shield', name: L('Омега-сварщик', 'Omega Welder'), description: L('Ваше существо потеряло щит — ваши заводчане получают +2/+2.', 'Whenever a friendly minion loses Divine Shield: your factory workers get +2/+2.'), tavernTier: 6, attack: 6, health: 6, keywords: ['divineShield'], tribes: ['mech'], effects: [{ trigger: 'shieldPop', target: 'friendly', tribe: 'mech', action: { kind: 'buff', attack: 2, health: 2 } }] },
  { id: 'ab-zoo-mogul', name: L('Порошенко-зверинец', 'Zoo Mogul Poroshenko'), description: L('В конце хода: случайное ваше существо получает +3/+3 за каждый тип на столе.', 'At the end of your turn: a random friendly minion gets +3/+3 for each minion type on your board.'), tavernTier: 6, attack: 8, health: 8, keywords: [], tribes: ['neutral'], effects: [{ trigger: 'endTurn', target: 'random', tribe: 'all', per: 'tribes', action: { kind: 'buff', attack: 3, health: 3 } }] },
];